embed/index.html, index.html
Can be merged only after devnet is updated
=> Update nearlib to 0.2.2

libs/wallet.js
=> Update localstorage keys to _v2 to avoid reading old data

Gemfile, _includes/footer.html, assets/index.css, login/index.html
Rebased https://github.com/nearprotocol/near-wallet/pull/21
=> Changes to the footer and "NOT allow" text

src/components/accounts/CreateAccountContainer.js, src/components/accounts/RecoverAccountContainer.js, src/components/accounts/SetRecoveryInfoContainer.js, src/components/common/Disclaimer.js
Based on top of https://github.com/nearprotocol/near-wallet/pull/38
=> Copy fixes

.dockerignore, Dockerfile, README.md, scripts/init_nginx.sh, scripts/wallet.nginx
Relevant: https://github.com/nearprotocol/near-wallet/issues/80
=> Add docker container

src/components/login/Login.js, src/components/login/LoginContainer.js
TODOs left:
* show status message in wallet as opposed to redirecting to success url
* icon for near shell
=> V0 for shell integration (adding key from a shell-generated url works)

src/components/common/Balance.js, src/components/common/Balance.test.js, src/components/dashboard/DashboardDetail.js, src/components/profile/ProfileDetails.js, src/components/responsive/PopupMenuTrigger.js, src/components/send-money/SendMoneyAmountInput.js, src/components/send-money/SendMoneySecondStep.js, src/components/send-money/SendMoneyThirdStep.js
change bug for displaying amount more than 21 digits
detail: make Big object to Big.toFixed()
=> Fix bug with displaying amount bigger than 21 digits

src/components/common/Balance.js, src/components/common/Balance.test.js, src/components/dashboard/DashboardDetail.js, src/components/profile/ProfileDetails.js, src/components/responsive/PopupMenuTrigger.js, src/components/send-money/SendMoneyAmountInput.js, src/components/send-money/SendMoneySecondStep.js, src/components/send-money/SendMoneyThirdStep.js
- delete milli token
- if amount is less than 0.00001 near token, show <0.00001 
- hover the amount to see absolute amount
- change style to style-components
=> change display for balance

posthtml.config.js, src/components/responsive/DesktopView.js, src/index.html, src/middleware/index.js
Trying out [Amplitude](https://amplitude.com). So far seems much more powerful and easy to use than GA, will add in addition to GA to start. 
Large free tier too.
=> Add Amplitude analytics tracking

package.json, src/components/dashboard/ActionsList.js, src/components/dashboard/DashboardActivity.js, src/components/dashboard/DashboardKeys.js, yarn.lock
https://github.com/nearprotocol/near-wallet/issues/242
=> Add time stamp in 'time ago' format to Activity items

src/actions/account.js, src/components/common/Balance.js, src/components/login/LoginDetails.js, src/components/sign/MobileContainer.js, src/components/sign/Sign.js, src/components/sign/SignAnimatedArrow.js, src/components/sign/SignContainer.js, src/components/sign/SignTransferCancelled.js, src/components/sign/SignTransferDetails.js, src/components/sign/SignTransferInsufficientFunds.js, src/components/sign/SignTransferReady.js, src/components/sign/SignTransferSuccess.js, src/components/sign/SignTransferTransferring.js, src/reducers/account/index.js, src/reducers/index.js, src/reducers/sign.js, src/utils/wallet.js
Reverts nearprotocol/near-wallet#277
=> Revert "Revert "Implement API for signing individual transaction""

src/components/Routing.js, src/components/responsive/DesktopView.js, src/components/responsive/MobileView.js, src/components/responsive/ResponsiveContainer.js
- Move some code up to ResponsiveContainer
- Clean up
=> Hide nav links during signup flow

package.json, src/components/common/Balance.js, src/components/common/Balance.test.js, src/components/send-money/SendMoneyAmountInput.js
this is due to the fact that nearcore now keeps account balance in units of
yoctonear
=> Update nomination so that wallet correctly displays account balance

src/actions/account.js, src/components/Routing.js, src/components/login/Login.js, src/utils/wallet.js
Reverts nearprotocol/near-wallet#291
Got problem logging in. Test by running app https://studio.nearprotocol.com/?f=ttyvb4ert  (change `walletUrl` in `src/main.js` as necessary) and trying to login. UI was showing that full access is requested for some reason.
Another problem I got – looks like persisted state gets in the way of new logins (same public key gets reused).
=> Revert "Persist redirect related state from clear after page reloads (#276)"

src/actions/account.js, src/components/sign/Sign.js, src/reducers/sign.js
For testing:
https://app.near.ai/app/ogrd4hurv/
https://studio.nearprotocol.com/?f=ogrd4hurv
=> Make callback work when signing transaction

src/components/receive-money/ReceiveMoney.js
This update enables copying the address url without showing it on the UI
=> Receive page: Hide address url from UI

src/components/responsive/ResponsiveContainer.js
https://github.com/nearprotocol/near-wallet/issues/408
=> Hide nav links during signup for new users

src/components/accounts/SetRecoveryMethod.js, src/components/accounts/SetRecoveryMethodContainer.js
- Remove flag border
- Remove orange outline on focus
- Remove inset shadow (webkit fix)
=> Phone input: fix styling

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md
Addresses: https://github.com/nearprotocol/near-wallet/issues/386
This is a request that came in a while ago, getting to it with the repos in closest reach.
I am not super familiar with this repo, but added some basics to the bottom of the README to run `./build_image.sh` but believe this could be fleshed out some more. If folks who touch this project more want to jump in on this PR that could be helpful. After running that command I got:
> Publish image to hub (y/n)? n
And said no. If we want to expand on this, that'd be great.
=> add code of conduct, contributing, license

package.json, src/components/GlobalStyle.js, src/components/accounts/AccountFormSection.js, src/components/accounts/CreateAccount.js, src/components/accounts/CreateAccountForm.js, src/components/accounts/SetupSeedPhrase.js, yarn.lock
[reCAPTCHA admin panel](https://www.google.com/recaptcha/admin/site/349864146)
=> Add reCaptcha v3

src/components/accounts/RecoverAccountSeedPhrase.js
Was not able to recover account with seed phrase. This fixes that.
=> Fix recover w/ seed phrase

src/utils/explorer-api.js
This allows querying betanet, devnet, etc
=> Make NEAR explorer WAMP topic configurable

src/components/login/Login.js, src/components/login/LoginConfirm.js
Fixes https://github.com/nearprotocol/near-wallet/issues/493 and some other improvements
=> Login UI fixes

src/components/access-keys/AccessKeys.js, src/components/access-keys/AccessKeysDeauthorize.js, src/components/access-keys/AccessKeysDeauthorizeConfirm.js, src/components/common/FormButton.js, src/components/common/PageContainer.js, src/components/contacts/ContactsRemove.js, src/components/dashboard/ActionsList.js, src/components/dashboard/KeyListItem.js, src/components/dashboard/ListItem.js, src/components/pagination/PaginationBlock.js, src/components/pagination/PaginationSubBox.js, src/components/profile/ProfileYourKeys.js, src/components/send-money/SendMoneyAmountInput.js, src/components/send-money/SendMoneyContainer.js
@vgrichina @kcole16 
Question: is Confirm functionality should be available for all full access keys?
I also added changes regarding TODO comments in code, and some additional:
- fixed publickey display in details box - there was a problem with displaying it for different screen sizes
- added loading effect for Deauthorize and Confirm buttons, because it takes some time to proceed deauthorize
- refactor `AccessKeysDeauthorize` component and ContactsRemove since they based on the same CSS from `PaginationSubBox` file.
=> Add confirm accountId functionality to deauthorize full access key and additional changes for Full Access Keys components

src/components/access-keys/AccessKeysDeauthorizeConfirm.js, src/components/login/LoginConfirm.js, src/translations/en.global.json
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/514"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/8d9272ab92d58d290b24ca384d40b237b635e2c6.svg" /></a>
=> Make user-visible strings localizable

src/components/accounts/AccountFormAccountId.js
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/513"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/0e02fb650e598017badb736780df4b587fceba0b.svg" /></a>
=> create account: include TLA when checking availability

src/components/accounts/AccountFormAccountId.js
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/516"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/ecda0cab4d575dc314a90120bdc9f135101a6758.svg" /></a>
=> fix account availability check

src/components/dashboard/ActionsList.js
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/525"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/de0de546914462c4be6bc6b2f4e845e8f87ab4e4.svg" /></a>
=> Fix timestamp in Activity Feed on Dashboard page (#519)

src/components/accounts/CreateAccount.js, src/utils/wallet.js
This was missed in https://github.com/nearprotocol/near-wallet/pull/535
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/536"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/c3b2ad323112d0e85998aa9d6e16974aa8fef69c.svg" /></a>
=> fix: env var no longer has dot; add dot when needed

src/actions/account.js, src/components/GlobalStyle.js, src/components/dashboard/ActionsList.js, src/components/dashboard/DashboardActivity.js, src/components/dashboard/DashboardDetail.js, src/components/dashboard/DashboardKeys.js, src/reducers/account/index.js, src/translations/en.global.json, src/utils/explorer-api.js, src/utils/wallet.js
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/526"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/17cc497eec8addd71181ab5446c9d4ef201eacf2.svg" /></a>
=> Transactions status (#519)

src/utils/wallet.js
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/537"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/7ab12ccc5e86117ad4a5b86a91c44cf6ee0dfbce.svg" /></a>
=> Change default account id suffix

src/components/dashboard/ActionsList.js
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/540"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/e522854b5a08f4f1b1d90094f54eb7c479f72b53.svg" /></a>
=> Display stake amount in yoctoNEAR (#538)

src/utils/wallet.js
Fixes https://github.com/near/near-wallet/issues/429
=> Handle error when adding duplicate access key

src/utils/wallet.js
=> Revert "Pass explicit storage prefix for BrowserLocalStorageKeyStore"

src/components/dashboard/DashboardDetail.js, src/components/login/LoginDetails.js, src/utils/wallet.js
To fix broken TX list 'view all' link when developing locally etc.
=> default explorer url to testnet

src/actions/account.js, src/components/GlobalStyle.js, src/components/accounts/AccountFormAccountId.js, src/components/accounts/AccountFormSection.js, src/components/accounts/CreateAccount.js, src/components/accounts/CreateAccountForm.js, src/components/accounts/RecoverAccountSeedPhrase.js, src/components/accounts/RecoverAccountSeedPhraseForm.js, src/components/common/RequestStatusBox.js, src/components/send-money/SendMoney.js, src/components/send-money/SendMoneyAmountInput.js, src/components/send-money/SendMoneyContainer.js, src/components/send-money/SendMoneyFirstStep.js, src/reducers/account/index.js, src/translations/en.global.json
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/523"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/fd603e4a2dfdf6139609d06d85053f1895385064.svg" /></a>
=> Validate account name input length (#511)

src/components/access-keys/AccessKeys.js, src/utils/wallet.js
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/517"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/4261d2248cc8c5d9794db3cc1b17246d7cf36260.svg" /></a>
=> Bring back Ledger

src/components/accounts/recovery_setup/SetupRecoveryMethod.js
This change should improve mobile experience, in particular:
- disable auto-capitalization
- use proper keyboard
- give suggestion to auto-complete
=> Use input type=email for email field

src/components/send-money/SendMoney.js, src/components/send-money/SendMoneyAmountInput.js, src/components/send-money/SendMoneyContainer.js, src/translations/en.global.json
Mostly Behavioral bugs. Will address UI improvements in [656](https://github.com/near/near-wallet/issues/656)
=> Send page fixes

src/components/Routing.js, src/components/navigation/NavLinks.js
https://github.com/near/near-wallet/issues/655
=> disable transfers on mainnet

src/components/GlobalStyle.js, src/components/accounts/ledger/SetupLedger.js, src/translations/en.global.json
=> ledger setup: copy updates

package.json, src/components/GlobalStyle.js, src/components/accounts/CreateAccount.js, src/components/accounts/CreateAccountForm.js, yarn.lock
https://github.com/near/near-wallet/issues/709
=> Remove reCAPTCHA

src/components/Routing.js, src/translations/cn.global.json
Moving https://github.com/near/near-wallet/pull/582 as cannot commit to it directly
=> Create Simplified Chinese translation

src/actions/account.js, src/components/accounts/CreateAccount.js, src/components/accounts/RecoverAccountSeedPhrase.js, src/components/accounts/RecoverWithLink.js, src/components/accounts/SetupSeedPhrase.js, src/components/accounts/ledger/SetupLedger.js, src/components/accounts/ledger/SignInLedger.js, src/components/accounts/recovery_setup/SetupRecoveryMethod.js, src/components/profile/Recovery/RecoveryContainer.js, src/components/profile/hardware_devices/HardwareDevices.js, src/components/send-money/SendMoney.js, src/components/sign/Sign.js, src/middleware/index.js
This allows to handle errors using `try` / `catch`, etc
Especially nice when it's necessary to chain multiple Redux actions.
=> Fix promise middleware return value

src/utils/wallet.js
Cherry-picked https://github.com/near/near-wallet/pull/792 into stable
=> Add more gas to linkdrop call

src/components/accounts/CreateAccount.js, src/components/common/styled/Container.css.js, src/components/landing/EmailSubscribe.js, src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
=> New Chinese translations

src/components/accounts/ledger/InstructionsModal.js, src/translations/en.global.json, src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
Add a step to "Install the latest firmware" to the Ledger Live instructions. Our app only shows up if the user has the latest firmware installed, and we've gotten several questions about this from users already.
=> Add step to ledger live instructions

src/actions/account.js, src/components/accounts/SetupSeedPhrase.js, src/components/accounts/recovery_setup/SetupRecoveryMethod.js, src/components/profile/Recovery/ActiveMethod.js, src/components/profile/Recovery/RecoveryContainer.js, src/components/profile/Recovery/RecoveryMethod.js, src/reducers/account/index.js, src/utils/wallet.js
Now creates account using the **recovery key** (seed phrase, phone, email). Once account creation is successful, it adds a new key to the account and localStorage. The result is one recovery key, and one localStorage key.
Dependency: https://github.com/near/near-contract-helper/pull/214 (https://near-contract-helper-2fa.onrender.com)
=> Create account w/ recovery key (email, phone, seed phrase)

src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
=> Update both Chinese translations

src/components/Routing.js
=> Show default translations on missing ones

src/components/accounts/recovery_setup/SetupRecoveryMethod.js, src/translations/en.global.json
Place the 'most secure' options above 'less secure' options.
=> recovery options: switch order

src/actions/account.js, src/components/accounts/SetupSeedPhrase.js, src/components/accounts/ledger/SetupLedger.js, src/components/accounts/recovery_setup/SetupRecoveryMethod.js, src/reducers/ledger/index.js, src/translations/en.global.json, src/utils/wallet.js
Create account with Ledger key instead of randomly generated key. Mainly to fix this https://github.com/near/near-wallet/issues/828
=> refactor create account w/ ledger

src/actions/account.js
Make sure the seed phrase is saved on chain before adding it to DB
=> setup seed phrase: save key on chain before db

src/components/accounts/recovery_setup/SetupRecoveryMethod.js, src/components/profile/Recovery/RecoveryContainer.js, src/utils/explorer-api.js, src/utils/helper-api.js, src/utils/wallet.js
=> use CH for accountIds

src/components/accounts/EnterVerificationCode.js, src/components/navigation/DesktopContainer.js, src/components/navigation/MobileContainer.js, src/translations/en.global.json, src/translations/ru.global.json, src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
=> New translations and fix

src/utils/twoFactor.js
Fixes trying to delete keys that are NOT part of account when deploying multisig.
=> Fix 2fa deploy multisig keys

src/components/GlobalStyle.js, src/components/accounts/AccountFormAccountId.js, src/components/accounts/RecoverAccountSeedPhrase.js, src/components/accounts/RecoverAccountSeedPhraseForm.js, src/translations/en.global.json, src/translations/ru.global.json, src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
Username -> Account ID
Account ID input sub label -> _Your account ID must include a Top Level Account such as **.near**_
=> change account id label, placeholder, and sub label

src/components/profile/Recovery/RecoveryContainer.js, src/reducers/account/index.js, src/utils/wallet.js
fix where recovery methods filters by any access key not only full access key
fixes #903
=> Fix recovery methods

src/utils/wallet.js
Fixes https://github.com/near/near-wallet/issues/950
=> Allow recovery of existing implicit accounts

src/components/accounts/RecoverAccount.js, src/components/landing/GuestLanding.js, src/images/icon-hardware-device.svg, src/translations/en.global.json
Changes:
- Add Ledger as option on recovery page
- Replace 'Recover your Account' with 'Access your Account'
- Remove 'Sign in with Ledger' cta from guest landing page
=> add ledger to recovery page

src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
=> Update Chinese translations

src/components/send-money/SendMoneyAmountInput.js
=> Revert "Add pattern to amount input field (#973)"

src/components/staking/StakingContainer.js, src/components/staking/components/AlertBanner.js, src/components/staking/components/BalanceBox.js, src/components/staking/components/Staking.js, src/components/staking/components/Validator.js, src/components/staking/components/Validators.js, src/components/svg/AlertTriangleIcon.js, src/translations/en.global.json, src/utils/staking.js
Includes:
1. Ability to view other validators profiles while actively staking
2. Show disclaimer banner on top of validators profile while actively staking
3. Re-set `selectedValidator` variable after withdrawing unstaked balance
4. Copy updates
=> Staking UI updates

src/components/staking/components/StakeConfirmModal.js
Copy update: Confirm & Send --> Confirm
=> Adjust stake btn copy

src/components/common/Balance.js, src/utils/staking.js
This PR requires unstaked amounts for validators to be greater than 100 yocto before being included in calculations for UI display
=> Fix rounding error

src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
=> Update Staking translations

src/translations/en.global.json
Fixing typo in explanation for 'rewards earned'.
=> Fix staking copy

src/components/staking/components/Validators.js
Filter the list of validators based on user input value while typing
=> filter validator list with user input

src/utils/account-with-lockup.js
releaseDuration=null caused weird problems accessing account for some users
=> Mainnet Wallet Hotfix: Fix releaseDuration handling

src/utils/wallet.js
solution to https://github.com/near/near-wallet/pull/1014 while preserving 2FA link recovery which was broken.
=> hotfix: fixes 2fa recovery links and also allows seed phrase to recover without 2fa

src/utils/twoFactor.js, src/utils/wallet.js
this is a better hotfix than #1037
=> merge #1040 to stable

src/actions/account.js, src/components/profile/Profile.js, src/components/profile/two_factor/TwoFactorAuth.js
Fixes:
1. 2FA date 
2. 2FA not showing as active after setup (page refresh was required)
=> Fix 2FA 'Active since'

src/utils/staking.js
=> pull state and check before unselect pool

src/utils/account-with-lockup.js, src/utils/wallet.js
Also duplicate accountIds in recovery loop
=> hotfix implicitKeys that are LAK not FAK

src/middleware/index.js
fix the wrong setting function for user profile
=> fix the wrong setting

src/actions/account.js, src/components/Routing.js, src/components/accounts/CreateAccount.js, src/components/accounts/SetupImplicit.js, src/components/accounts/SetupSeedPhrase.js, src/components/accounts/SetupSeedPhraseForm.js, src/components/accounts/ledger/SetupLedger.js, src/components/accounts/recovery_setup/SetupRecoveryMethod.js, src/components/landing/GuestLanding.js, src/components/navigation/CreateAccountBtn.js, src/components/profile/Recovery/InactiveMethod.js, src/utils/wallet.js
This is a bit work in progress (you need to know URL http://wallet.testnet.near.org/create-from/your-account.testnet), but generally should be releasable.
=> Allow to fund account creation from another account

src/components/accounts/EnterVerificationCode.js, src/components/accounts/recovery_setup/SetupRecoveryMethod.js
@mattlockyer @Patrick1904 @marcinbodnar let's make sure we handle this for all forms
=> Make sure to disable input fields when submitting form

src/utils/account-with-lockup.js
Addresses big part of https://github.com/near/near-wallet/issues/1035
=> Allow to destroy lockup and transfer remaining tokens

package.json, src/components/access-keys/AccessKeysEmpty.js, yarn.lock
Includes fix from https://github.com/near/near-api-js/pull/449
And Browse Apps link as drive-by.
=> Hotfix: Fix app login with 2FA

src/middleware/index.js
1. add function `identity` for user profile setting pre-requisite
2. fix some setting for user profile setting.
=> fix identify and setting for user profile

src/components/common/SkeletonLoading.js, src/components/staking/StakingContainer.js, src/components/staking/components/Staking.js
Added a loading animation to `/staking` page to make it more clear to users when data is being fetched.
=> Add loading animation to staking dashboard

src/actions/account.js, src/components/access-keys/AccessKeys.js, src/components/accounts/ledger/SetupLedger.js, src/components/profile/hardware_devices/HardwareDevices.js, src/utils/wallet.js
Changes:
1. Delete `connectLedger` and use `addLedgerAccessKey` for **enabling** and **reconecting** the Ledger.
=> Clean up reconnect Ledger

src/utils/wallet.js
Introduced by missing await here https://github.com/near/near-wallet/pull/1171/files
=> Fix crash when connecting Ledger

package.json, src/actions/account.js, src/components/staking/components/Validator.js, src/translations/en.global.json, src/utils/wallet.js, yarn.lock
=> Revert "Release 2020-12-23"

package.json, src/actions/account.js, src/components/staking/components/Validator.js, src/translations/en.global.json, src/utils/wallet.js, yarn.lock
Reverts near/near-wallet#1325
Updates near-api-js to include backwards compatibility fix
=> Release 2020-12-23 reboot

src/components/staking/StakingContainer.js, src/components/staking/components/StakeConfirmModal.js, src/components/staking/components/Staking.js, src/components/staking/components/StakingAction.js, src/components/staking/components/ValidatorBox.js
Fixes props on usages of ValidatorBox and links to Validator profiles.
=> Fix ValidatorBox props

src/utils/wallet.js
Fixes https://github.com/near/near-wallet/issues/1296
=> Recover implicit account with link if it exists

src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
Update both Chinese translations to latest code. Please review.
=> Update Chiense translations

src/components/Routing.js, src/components/accounts/AccountFormAccountId.js, src/components/accounts/CreateAccount.js, src/components/accounts/RecoverAccount.js, src/components/accounts/RecoverAccountSeedPhrase.js, src/components/accounts/RecoverWithLink.js, src/components/accounts/SetupImplicit.js, src/components/accounts/SetupImplicitSuccess.js, src/components/accounts/SetupSeedPhrase.js, src/components/accounts/ledger/SetupLedger.js, src/components/accounts/ledger/SetupLedgerSuccess.js, src/components/accounts/ledger/SignInLedger.js, src/components/accounts/recovery_setup/SetupRecoveryMethod.js, src/components/accounts/two_factor/EnableTwoFactor.js, src/components/accounts/two_factor/TwoFactorVerifyModal.js, src/components/dashboard/DashboardDetail.js, src/components/navigation/AccessAccountBtn.js, src/components/navigation/CreateAccountBtn.js, src/components/profile/Profile.js, src/components/profile/Recovery/ActiveMethod.js, src/components/profile/Recovery/InactiveMethod.js, src/components/profile/Recovery/RecoveryContainer.js, src/components/profile/hardware_devices/HardwareDevices.js, src/mixpanel/index.js
create tracking flow for:
1. creating new account 
2. import existing account
3. setup recovery method
=> finish create account flow

src/components/dashboard/ActionsList.js
Tiny improvement to make it easier to find transactions in explorer
=> Add links to transactions in explorer

src/components/Routing.js
fix the bug for error message is undefined
=> fix the issue

src/components/Routing.js, src/components/accounts/two_factor/TwoFactorVerifyModal.js
add tracking for success verification 2FA modal one
=> add verify success

src/components/navigation/DesktopContainer.js, src/components/navigation/MenuButton.js, src/components/navigation/MobileContainer.js, src/components/navigation/Navigation.js
Show limited nav items on `/sign` route to prevent user from switching account
=> Show limited nav items on /sign route

netlify.toml, src/components/accounts/SetupSeedPhrase.js, src/components/accounts/ledger/InstructionsModal.js, src/components/accounts/recovery_setup/SetupRecoveryMethod.js, src/components/accounts/two_factor/EnableTwoFactor.js, src/components/landing/EmailSubscribe.js, src/components/landing/GuestLanding.js, src/components/wallet/Activities.js, src/components/wallet/ActivityDetailModal.js, src/components/wallet/ExploreApps.js, src/mixpanel/index.js
1. update tracking with new design and small issues
2. change token to new one
=> Polish and improve track and change for new token

src/components/profile/Profile.js
=> Profile: fix check for authorizedApps

src/components/common/NetworkBanner.js, src/components/profile/Profile.js, src/mixpanel/index.js
1. delete some private property for user
2. add network id property
=> finish build

src/components/accounts/SetupImplicit.js, src/components/common/AlertBanner.js, src/translations/en.global.json
Changes:
1. Funding page: add banner that says 'Do not close this window!'
=> Fund account page: add banner

netlify.toml, src/components/common/ClickToCopy.js
1. fix the code for copy account with link 
2. update token
=> fix the tracking for copy

package.json, src/actions/account.js, src/components/sign/Sign.js, src/reducers/sign.js, src/utils/wallet.js, yarn.lock
Needs this 2 PRs to work:
https://github.com/near/near-contract-helper/pull/347
https://github.com/near/near-api-js/pull/529
=> Allow to pass metadata with transaction to sign

src/components/GlobalStyle.js
=> font: slashed-zero

src/actions/account.js, src/actions/flowLimitation.js, src/utils/account-with-lockup.js, src/utils/wallet.js
Cherry-picking https://github.com/near/near-wallet/pull/1583
=> Hotfix: Load basic balance data only for Sign page

src/components/wallet/Wallet.js
Depends on https://github.com/near/near-contract-helper/pull/322
- Most likely candidates for token contracts loaded from contract helper
- If required methods are missing tokens are ignored
- `localStorage` caching of the metadata
=> Load tokens list from contract helper

netlify.toml, src/components/accounts/two_factor/EnableTwoFactor.js, src/components/common/AlertBanner.js, src/translations/en.global.json, src/utils/wallet.js
Changes:
1. Footer: Change 'Need Help?' -> 'Questions?'
2. Enable 2FA: Add checkbox for 2FA storage amount acknowledgment
3. Enable 2FA: Update storage amount to 4 NEAR
=> UI fixes/updates

src/components/profile/two_factor/TwoFactorAuth.js
Do simplest possible change to enable 2FA (without key rotation as in https://github.com/near/near-wallet/pull/1344)
Key rotation should be unnecessary given nearcore changes around the issue.
Fixes https://github.com/near/near-wallet/issues/1086
=> Enable Disable 2FA

src/components/common/GlobalAlert.js, src/translations/en.global.json
Easiest way to test: go to https://near-wallet-pr-1723.onrender.com/sign-in-ledger using a Safari browser
=> globalAlert error: add link to Zendesk FAQ

src/actions/account.js, src/components/Routing.js, src/components/access-keys/AccessKeys.js, src/components/common/GuestLandingRoute.js, src/components/common/PageContainer.js, src/components/common/PrivateRouteLimited.js, src/components/login/Login.js, src/components/login/LoginForm.js, src/components/login/SelectAccountDropdown.js, src/components/navigation/DesktopContainer.js, src/components/navigation/DesktopMenu.js, src/components/navigation/MobileContainer.js, src/components/navigation/Navigation.js, src/components/navigation/UserAccounts.js, src/components/profile/Profile.js, src/components/profile/ProfileQRCode.js, src/components/profile/Recovery/RecoveryContainer.js, src/components/profile/hardware_devices/HardwareDevices.js, src/components/receive-money/ReceiveMoney.js, src/components/send/SendContainer.js, src/components/sign/Sign.js, src/components/sign/SignTransferReady.js, src/components/staking/StakingContainer.js, src/components/wallet/Activities.js, src/components/wallet/Wallet.js, src/reducers/account/index.js, src/reducers/allAccounts.js
=> Revert "Revert "Show UI instantly (#1665)""

src/translations/pt.global.json
This is a PR to update the NEAR Wallet Portuguese translation.
It's an initiative from [NEAR Portuguese Guild](https://www.notion.so/makersnetwork/Comunidade-NEAR-Portugu-s-f385ce229c5444468b9b9c6073e6e5db)
* Running local
=> Update Portuguese terms and translations

src/actions/account.js, src/components/accounts/RecoverWithLink.js, src/components/accounts/SetupImplicitSuccess.js, src/components/accounts/ledger/SetupLedger.js, src/utils/wallet.js
Changes:
1. Make dashboard the default redirect page (vs /profile)
=> Make dashboard the default redirect page (vs /profile)

src/components/pagination/PaginationSubBox.js
=> Fix padding for items and fix icon size in "Authorized Apps" page.

src/translations/pt.global.json
Update the sentence from "está solicitando para acesse sua conta" to "está solicitando para acessar sua conta".
=> Minor improvement to Portuguese translation

src/components/accounts/auto_import/AutoImport.js
**Example URL:**
https://near-wallet-pr-1838.onrender.com/auto-import-seed-phrase?success_url=https://google.com&failure_url=https://apple.com#knee%20sunny%20grow%20cry%20horn%20census%20lift%20final%20shoe%20inhale%20wait%20surge
**Important note:**
Any `success_url` or/and `failure_url` **must come before the Seed Phrase or/and Account ID** (see example URL above) cc @mattlockyer
=> Auto import seed phrase: support success_url and failure_url

src/actions/nft.js
https://github.com/near/near-wallet/issues/1845
=> Fix limit must number by NEP-181

src/actions/nft.js
Reverts near/near-wallet#1847
@ilyar we've accepted your change and it's now available on the [testnet](http://wallet.testnet.near.org/) and [staging](http://wallet.staging.near.org/) versions of the Wallet. We are planning a production release on Thursday at the latest, at which point the change will be on live in the [mainnet](https://wallet.near.org/) version of the Wallet.
Thanks again for your contribution.
=> Revert "Revert "Fix limit must number by NEP-181""

src/components/accounts/EnterVerificationCode.js, src/components/accounts/RecoverAccountSeedPhrase.js, src/components/accounts/SetupSeedPhrase.js, src/components/accounts/SetupSeedPhraseVerify.js, src/components/accounts/ledger/SetupLedger.js, src/components/accounts/ledger/SignInLedger.js, src/components/accounts/recovery_setup/SetupRecoveryMethod.js, src/utils/parseFundingOptions.js
=> Revert "Create account: Modify cases where reCaptcha prompt is displayed to the user"

src/components/wallet/Wallet.js, src/translations/en.global.json, src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
Add Simplified and Traditional Chinese support for NFT components
=> add zh language support for NFTs

src/components/accounts/EnterVerificationCode.js, src/components/accounts/RecoverAccountSeedPhrase.js, src/components/accounts/SetupSeedPhrase.js, src/components/accounts/SetupSeedPhraseVerify.js, src/components/accounts/ledger/SetupLedger.js, src/components/accounts/ledger/SignInLedger.js, src/components/accounts/recovery_setup/SetupRecoveryMethod.js, src/utils/parseFundingOptions.js
=> Revert "Revert "Create account: Modify cases where reCaptcha prompt is displayed to the user""

package.json, src/components/Routing.js, src/components/profile/Profile.js, src/components/staking/StakingContainer.js, src/components/wallet/Wallet.js, src/utils/reportUiActiveMixpanelThrottled.js, yarn.lock
update wallet balance loading event as Stefano asked
add event loading to calculate how many accounts are open and how many times are open
=> Add low-level Mixpanel event to facilitate MAU and DAU calculations

src/components/Routing.js, src/components/accounts/create/ActivateAccount.js, src/reducers/account/index.js, src/translations/en.global.json, src/translations/pt.global.json, src/translations/ru.global.json, src/translations/vi.global.json, src/translations/zh-hans.global.json, src/translations/zh-hant.global.json, src/utils/wallet.js
Changes:
1. Refactor 'isInactiveAccount' state and funded account status checking
2. Fix missing translations for `vi` lang and style adjustment
=> Refactor 'isInactiveAccount' state and checking

src/components/accounts/create/status/Style.css.js, src/components/receive-money/components/AccountId.js, src/components/receive-money/components/AccountIdQRCode.js, src/components/send/components/BalanceDetails.js, src/components/send/components/Receipt.js, src/components/send/components/SelectTokenButton.js, src/components/send/components/TokenIcon.js, src/components/send/components/TransactionDetails.js, src/components/send/components/entry_types/Amount.js, src/components/send/components/entry_types/Information.js, src/components/send/components/entry_types/Token.js, src/components/send/components/entry_types/css/Style.css.js, src/translations/en.global.json
_Effort part of https://github.com/near/near-wallet/issues/1714_
New components:
1. TransactionDetails.js
2. Information.js (entry type)
3. AccountId.js
4. AccountIdQRCode.js
5. SelectTokenButton.js
Modifications:
1. Moved TokenIcon.js out into its own file
2. Various style adjustments
3. Various translate-related naming changes
=> FT transfer: Add remaining smaller components and style adjustments

src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
Some change to the landing page description per the feedback from Amos and other users. 
Let's try to incorporate this change into this week's release if possible. Thanks!
**Simplified Chinese**
**Traditional Chinese**
=> Update Landing Page title and description for Chinese translations

src/components/wallet/Tokens.js
🐑  :) Explicit key for NEAR tokens which don't have a contractName :)
=> Add key fallback for NEAR tokens

src/components/Routing.js, src/components/send/components/TabSelector.js
Replaces current send/receive flows with the new one: https://github.com/near/near-wallet/issues/1714
=> Activate new FT transfer flow

src/components/navigation/DesktopContainer.js, src/components/navigation/SendReceiveButtons.js, src/components/send/SendContainerV2.js, src/components/send/SendContainerWrapper.js, src/components/wallet/Wallet.js
Changes:
1. Add send/receive buttons to desktop nav
2. Do not reset transfer amount when switching token
3. Add Mixpanel tracking events that are present in current/legacy send flow
=> FT transfer follow-up fixes

src/components/send/SendContainerV2.js, src/components/send/components/views/Review.js
Changes:
1. FT transfer, switch account: reset everything
2. Review page: only disable buttons if `sendingToken === true`
=> FT transfer fixes

src/components/send/components/AmountInput.js, src/components/send/components/SelectTokenButton.js, src/components/send/components/entry_types/Token.js, src/components/send/components/entry_types/css/Style.css.js, src/components/send/components/views/EnterAmount.js, src/components/send/components/views/EnterReceiver.js, src/components/wallet/TokenBox.js, src/components/wallet/Wallet.js
Changes:
1. Add box shadow to token icons
2. Wallet/dashboard: remove NEAR icon and use Textfix for total balance
3. Token list: prevent selecting token when clicking on token contract link
4. FT transfer, enter amount: fix number jumping when entering first character on mobile
5. FT transfer, enter receiver: use Textfit for amount
=> FT UI fixes

src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
Update Two Factor Authentication from "两步验证" to "双重认证"
=> Update Translation of Two-Factor Authentication

src/translations/zh-hans.global.json, src/translations/zh-hant.global.json
=> Update Chinese translations #1973

src/components/navigation/DesktopContainer.js, src/components/navigation/UserAccounts.js, src/components/wallet/Wallet.js, src/translations/en.global.json
Changes:
1. Nav account balance: remove almost equal sign from USD balance
2. Adjust total/avail balance copy
3. Desktop nav: remove send/receive buttons
=> Balance display fixes

README.md, packages/e2e-tests/LICENSE, packages/e2e-tests/LICENSE-APACHE, packages/frontend/LICENSE, packages/frontend/LICENSE-APACHE
=> Lerna - add top-level README.md and add license copies to frontend & e2e-tests

packages/frontend/src/translations/en.global.json
Simple text change.
Signed-off-by: Dylan Schultz <dylanschultz311@gmail.com>
=> Fix typo in footer

packages/e2e-tests/package.json, packages/e2e-tests/register/models/CreateAccount.js, packages/e2e-tests/register/models/Home.js, packages/e2e-tests/register/seedPhrase.spec.js, packages/e2e-tests/transfer-tokens/models/SendMoney.js, packages/e2e-tests/transfer-tokens/transfer-token.spec.js, packages/e2e-tests/utils/account.js, packages/e2e-tests/yarn.lock, packages/frontend/src/components/send/components/AmountInput.js, packages/frontend/src/components/send/components/BalanceDetails.js, packages/frontend/src/components/send/components/InputAccountId.js, packages/frontend/src/components/send/components/SelectTokenButton.js, packages/frontend/src/components/send/components/entry_types/Amount.js, packages/frontend/src/components/send/components/views/EnterAmount.js, packages/frontend/src/components/send/components/views/EnterReceiver.js, packages/frontend/src/components/send/components/views/Review.js, packages/frontend/src/components/send/components/views/Success.js, packages/frontend/src/components/wallet/TokenBox.js, packages/frontend/src/components/wallet/Wallet.js
End to end tests for transferring NEAR (Currently 0.1 Ⓝ) between two accounts created by the test and deleted after. 
Add / extend the following POMs
* Send Money page `/send-money`
* Home page  `/` - added methods to login using seed phrase / key pair by setting localStorage
=> Transfer tokens e2e tests

packages/frontend/src/translations/en.global.json
Fixed incorrect verbiage about our most release released features :)
=> Fix verbiage about new functionality

packages/frontend/src/components/Routing.js, packages/frontend/src/components/SafeTranslate.js, packages/frontend/src/components/accounts/create/verify_account/VerifyAccount.js, packages/frontend/src/components/accounts/create/verify_account/VerifyAccountWrapper.js
This is why we can't have nice things :( :)
=> Disable email verification

packages/frontend/netlify.toml, packages/frontend/package.json, packages/frontend/src/components/accounts/create/verify_account/VerifyAccountWrapper.js, packages/frontend/src/index.js, packages/frontend/src/utils/wallet.js, packages/frontend/yarn.lock
=> Add Recaptcha Enterprise

packages/frontend/src/components/accounts/create/verify_account/VerifyAccountWrapper.js, packages/frontend/src/translations/en.global.json
Added error handling for recaptcha failures and invalid email provider responses during verified account creation flow
=> Email verification error handling

packages/frontend/src/components/accounts/create/verify_account/VerifyAccount.js, packages/frontend/src/components/accounts/create/verify_account/VerifyAccountWrapper.js
=> Re-enable verified account creation using e-mail address

packages/frontend/src/translations/zh-hans.global.json
Updated the translation of new version
=> Updated the translation of new version 

packages/frontend/src/translations/zh-hant.global.json
Updated the translation of new version
=> Updated the translation of new version

packages/frontend/netlify.toml, packages/frontend/src/components/accounts/CreateAccount.js, packages/frontend/src/components/accounts/recovery_setup/SetupRecoveryMethod.js, packages/frontend/src/components/profile/Recovery/RecoveryContainer.js, packages/frontend/src/utils/wallet.js
- Toggleable via environment variable :)
- Still allows disabling of existing SMS recovery methods for those who have previously used this functionality.
=> Disable SMS recovery methods

packages/frontend/src/components/accounts/SetupImplicit.js, packages/frontend/src/components/accounts/create/initial_deposit/InitialDepositWrapper.js, packages/frontend/src/components/accounts/create/verify_account/VerifyAccountWrapper.js
Add tracking for:
1. Moonpay events
2. Check implicit address funding status
3. Create account from implicit
=> Coin-op 1.5: Add missing tracking

packages/frontend/src/utils/wallet.js
fix `indexOf(``ccount...` with `indexOf(``account...`
=> fix typo in wallet.js error handling

packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
=> Improve and fix translation typo

packages/frontend/src/components/login/v2/ConfirmLogin.js, packages/frontend/src/components/login/v2/ConfirmLoginWrapper.js, packages/frontend/src/components/login/v2/NetworkFeeAllowance.js, packages/frontend/src/routes/LoginWrapper.js, packages/frontend/src/translations/en.global.json, packages/frontend/src/translations/pt.global.json, packages/frontend/src/translations/ru.global.json, packages/frontend/src/translations/vi.global.json, packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
=> App login: Add info about app key allowance

packages/frontend/src/components/accounts/ledger/SignInLedger.js, packages/frontend/src/components/common/AlertBanner.js, packages/frontend/src/translations/en.global.json, packages/frontend/src/translations/pt.global.json, packages/frontend/src/translations/ru.global.json, packages/frontend/src/translations/vi.global.json, packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
=> Sign in w/ Ledger: Add Firefox disclaimer banner

packages/frontend/src/redux/slices/nft/index.js
Added `updateNFTs` thunk that is part of transfer NFT functionality. It allows clearing tokens for one contract and fetching the new list of contracts, or clearing tokens for all contracts - depending on the `contractName` param.
=> Add updateNFTs thunk

packages/frontend/src/redux/slices/staking/index.js
Set of selectors to be used for staking reducer.
=> Selectors for staking actions

packages/frontend/src/translations/en.global.json, packages/frontend/src/utils/wallet.js
Account for testing:
accountId: `tryagain.near`
seed phrase: `(redacted)`
=> Fix redirect after LackBalanceForState error

packages/frontend/src/redux/reducers/selectors/balance.js, packages/frontend/src/redux/slices/transactions/index.js
=> 2021-12-22 Release

packages/frontend/src/components/wallet/NFTs.js
=> https://github.com/near/near-wallet/issues/2330

packages/frontend/src/components/accounts/create/implicit_account/CreateImplicitAccount.js, packages/frontend/src/routes/CreateImplicitAccountWrapper.js
=> fix: replace MoonPay pre-specified amount buttons w/ generic 'Buy with MoonPay'

packages/frontend/src/translations/tr.global.json
authentic Turkish translation of Near Wallet Jan 2022
=> Turkish.global.json

packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
=> New translations

packages/frontend/src/redux/actions/account.js, packages/frontend/src/redux/slices/sign/index.js
Fixes logic that appends additional query params to urls with existing query params.
Closes #2442
=> fix: fix logic to append additional query params

packages/frontend/src/redux/actions/account.js, packages/frontend/src/redux/slices/sign/index.js
Re-adds missed pathname when reconstructing url
Closes #2442
=> fix: re-add missed pathname when reconstructing url

lerna.json, package.json, packages/e2e-tests/CHANGELOG.md, packages/e2e-tests/package.json, packages/feature-flags/CHANGELOG.md, packages/feature-flags/package.json, packages/frontend/CHANGELOG.md, packages/frontend/package.json, packages/frontend/src/components/accounts/recovery_setup/SetupRecoveryMethod.js, yarn.lock
- Autogenerated CHANGELOG.md for each package using conventional commits.
- Configured subsequent update of changelog in `lerna.json`
- Added standard commit message support in package scripts, so those who aren't yet familiar with the supported keywords can create appropriate commit messages using the CLI prompt. Simply run `yarn run commit`.
Addresses Issue #2354
=> Tooling: Auto generate changelog using conventional commits

packages/frontend/.eslintrc.js, packages/frontend/src/redux/actions/account.js, packages/frontend/src/redux/slices/sign/index.js
revert `query-string` stringify append changes to stable
=> fix: revert query-string append changes

packages/frontend/src/components/profile/two_factor/TwoFactorAuth.js
Hotfix for https://github.com/near/near-wallet/issues/2261
=> Prevent wallet from deploying 2FA to account with existing contract

packages/frontend/src/components/accounts/RecoverWithLink.js, packages/frontend/src/components/accounts/recovery_setup/RecoveryOption.js
Fixes some unnoticed UI quirks from the removal of Semantic UI.
- fix: /recover-with-link container
=> fix: Broken styling from Semantic UI removal

packages/frontend/src/components/accounts/create/verify_account/VerifyOption.js, yarn.lock
=> fix: radio button

packages/frontend/src/components/common/GlobalAlert.js, packages/frontend/src/translations/en.global.json, packages/frontend/src/utils/wallet.js
This PR adds the seed phrase public key to the error message when seed phrase recovery fails. I've also fixed several typos in adjacent code.
Closes #2386
=> WAL-126: Import failure show public key

packages/frontend/src/routes/CreateImplicitAccountWrapper.js
This PR fixes the reference to `checkAndHideLedgerModal`
=> fix(ledger): use the new action reference

packages/frontend/src/components/staking/components/Validator.js
Only claim all tokens on withdrawal if the validator is a staking farm validator.
Closes #2548
=> fix: add conditional claim all on withdraw

packages/frontend/src/components/staking/components/Validator.js, packages/frontend/src/redux/crossStateSelectors/selectNEARAsTokenWithMetadata.js
=> 2022-03-25 Release

packages/frontend/src/components/Routing.js, packages/frontend/src/components/navigation/Navigation.js, packages/frontend/src/components/navigation/NavigationWrapper.js, packages/frontend/src/components/wallet/Wallet.js, packages/frontend/src/routes/WalletWrapper.js
Changes:
1. Wrappify main dashboard (`Wallet.js`) and Navigation components as part of zero balance wallet support
2. Convert from class components to function components
=> chore: Wrappify Dashboard and Navigation components

packages/frontend/src/components/accounts/create/implicit_account/CreateImplicitAccount.js, packages/frontend/src/routes/CreateImplicitAccountWrapper.js
=> fix: Create implicit: Fix MoonPay button loading state

packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
Update new Chinese translations
=> feat: update new Chinese translations

packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
update Chinese translation for swap feature on behalf of @RubyJiao
=> update zh translation for swap

packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
add the missing translation as mentioned here: https://github.com/near/near-wallet/pull/2591#issuecomment-1105913862
=> fix: missing zh translation

features/flags.json
=> enabled flag USN on mainnet

features/flags.json
=> fix: revert USN feature

packages/frontend/src/components/Routing.js, packages/frontend/src/utils/account-with-lockup.js
In this PR:
- Fixes error with missing method call when accessing lockup profiles
=> BUGFIX: error when loading profile page on wallet see screenshot

features/flags.json
refactor: disable usn on mainnet
=> refactor: disable usn on mainnet

packages/frontend/src/translations/vi.global.json
Some Vietnamese sentences was not translated correctly or was not translated so we have updated them. (Reviewed by CuongDCDev)
=> fix: review and update Vietnamese translation

features/flags.json
Add missing feature flags for new environments to flags.json
=> fix: add missing flags

features/features.d.ts, features/flags.json, packages/frontend/src/components/navigation/NavLinks.js, packages/frontend/src/components/svg/DonateToUkraineIcon.js, packages/frontend/src/translations/en.global.json, packages/frontend/src/translations/pt.global.json, packages/frontend/src/translations/ru.global.json, packages/frontend/src/translations/tr.global.json, packages/frontend/src/translations/ua.global.json, packages/frontend/src/translations/vi.global.json
Updated PR "Donate to Ukraine"
=> Updated PR "Donate to Ukraine"

features/flags.json, packages/frontend/src/components/navigation/NavLinks.js, packages/frontend/src/translations/en.global.json, packages/frontend/src/translations/ua.global.json
* Add missing `USN_LOGO` import 
* Add missing environments for new `DONATE_TO_UKRAINE` flag
* lint fixes
=> Add missing env for flag

features/flags.json
This PR enables use of the new indexer service endpoint URL in mainnet
=> feat(indexer): enable USE_INDEXER_SERVICE in mainnet

packages/frontend/src/components/accounts/ledger/SetupLedger.js
1. open incognito browser window
2. recover account using seed phrase
3. go to Account page and Enable Ledger
4. try for example to send near
=> Custom hd path fix

packages/frontend/src/translations/en.global.json
This PR is fixing translation for Connect Ledger modal, which appears if you click Connect Ledger button.
=> Fix connect ledger modal translation

packages/frontend/test/feature_flags.test.js
This PR adds a test to ensure that all feature flags have a key for every valid environment.
=> test(flags): verify that every feature flag specifies every environment

packages/frontend/src/components/navigation/DesktopContainer.js
=> fix: Fix desktop nav horizontal overflow

packages/frontend/src/components/navigation/NavLinks.js, packages/frontend/src/components/wrap/components/SwapFromTo.js, packages/frontend/src/translations/en.global.json, packages/frontend/src/translations/pt.global.json, packages/frontend/src/translations/ru.global.json, packages/frontend/src/translations/tr.global.json, packages/frontend/src/translations/ua.global.json, packages/frontend/src/translations/vi.global.json, packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
=> Chinese translations

features/flags.json
Give it a whirl: https://deploy-preview-2699--glittering-pavlova-0e9247.netlify.app/
=> chore: Turn 'zero balance account' on in testnet and staging env

packages/frontend/src/components/Routing.js, packages/frontend/src/translations/it.global.json
This PR adds Italian translation files.
Resolves #2267
=> feat(translation): Italian translation

packages/frontend/src/components/nft/NFTMedia.js
- Allow rendering of `.mp4` videos in addition to `.webm`
=> Add mp4 support

packages/frontend/src/components/accounts/ledger/InstructionsModal.js, packages/frontend/src/translations/en.global.json
In this PR:
- Updates outdated ledger instructions and copy
=> feat: update ledger instructions

packages/frontend/src/components/accounts/account_selector/AccountSelector.js
Resurrecting #2121 
Closes #2069
=> style: scroll bar on accounts dropdown

packages/frontend/src/components/buy/FundingType.jsx, packages/frontend/src/config/buyNearConfig.js
Custom local environment allowed to use ref param, but it's broken on default react.
=> Rename ref prop to provideReferrer.

packages/frontend/src/components/wallet/ActivitiesWrapper.js, packages/frontend/src/components/wallet/ActivityDetailModal.js, packages/frontend/src/redux/slices/transactions/index.js
Introducing solution: Using entity adapter to perform CRUD operations on the transactions array.
=> Use createEntityAdapter for transactions reducer

.github/CODEOWNERS, Jenkinsfile
This PR updates the Jenkinsfile to deploy to S3 buckets in the new AWS frontend accounts.
=> feat(ci): Jenkins deployment

packages/frontend/src/redux/crossStateSelectors/selectCollectedAvailableForClaimData.js, packages/frontend/src/services/StakingFarmContracts.js, packages/frontend/src/utils/account-with-lockup.js
=> Revert "Wal 277 withdrawing lockup funds issue"

packages/frontend/src/redux/crossStateSelectors/selectCollectedAvailableForClaimData.js, packages/frontend/src/services/StakingFarmContracts.js, packages/frontend/src/utils/account-with-lockup.js
Recreates #2623 with fix for typo
=> Wal 277 withdrawing lockup funds issue fix

packages/frontend/src/components/accounts/batch_ledger_export/index.js
Adds missing `onCancel` functionality for when the user clicks "Cancel" on the batch ledger export route
=> fix: add onCancel functionality

packages/frontend/src/config/buyNearConfig.js
This is a request from the legal team and we need to accept this PR asap. Agreed with George Goshanov.
=> Changed the nearpay link

packages/frontend/src/components/common/Footer.js, packages/frontend/src/redux/actions/staking.js
Changed footer link from near chat to discord channel
=> fix: changed footer community link to discord channel

packages/frontend/src/hooks/fungibleTokensIncludingNEAR.js, packages/frontend/src/redux/slices/tokenFiatValues/index.js
The Jenkins pipeline is failing on `master` because of some breaks to the new eslint rules, seems like PRs haven't been triggering CI builds consistently 🤔
=> style: lint fixes

packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
=> feat: add new Chinese translations

packages/frontend/src/components/accounts/CreateAccount.js, packages/frontend/src/components/accounts/TermsModal.js, packages/frontend/src/translations/en.global.json, packages/frontend/src/translations/it.global.json, packages/frontend/src/translations/pt.global.json, packages/frontend/src/translations/ru.global.json, packages/frontend/src/translations/tr.global.json, packages/frontend/src/translations/vi.global.json, packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
=> fix: MYNW-85 update privacy link

features/features.d.ts, features/flags.json, packages/frontend/src/components/Routing.js
This PR adds feature flags to limit web3-auth availability strictly to testnet
=> feat: added WEB3AUTH feature flag

packages/frontend/src/hooks/fungibleTokensIncludingNEAR.js, packages/frontend/src/utils/fiatValueManager.js
=> 2022-07-21 Release 2

packages/frontend/src/components/send/components/InputAccountId.js, packages/frontend/src/components/send/components/ReceiverInputWithLabel.js, packages/frontend/src/components/send/components/views/EnterReceiver.js
Fixed implicit account validation.
this is second part of https://github.com/near/near-wallet/pull/2849
=> [Draft] Fixed implicit account for Mynw-108

packages/frontend/src/components/send/components/RiscScoringForm.js
Fixed style for https://github.com/near/near-wallet/issues/2846
=> Fix/tuned risc-scoring checkbox style

packages/frontend/src/components/send/components/RiscScoringForm.js
Add analytics for HAPI usage and detected scam addresses
=> Added MixPanel analytics to hapi

.github/workflows/pull-request.yml
This PR updates the PR workflow to run lint and test for the frontend package.
=> ci: Run lint/test on PRs

packages/frontend/src/components/nft/NFTTransferModal.js
This is the hotfix for sending NFT
Problem: https://twitter.com/WeaponX_78/status/1555672711401295873?s=20&t=1Snr-woqQ6SKeAJpLzmoww
@PinkiNice @Patrick1904
=> hotfix: Sending NFT

packages/frontend/src/config/configFromEnvironment.js, packages/frontend/src/translations/en.global.json
fix: update migration banner copy
=> fix: update migration banner copy

packages/frontend/src/components/common/MigrationBanner.js
=> fix: update url to point to blog for migration banner

packages/frontend/src/components/navigation/NavLinks.js
Replaced Zendesk with Intercom for MyNearWallet
=> feat: MYNW-106  replaced zendesk with intercom for mynearwallet

packages/frontend/src/redux/slices/tokenFiatValues/index.js, packages/frontend/src/utils/fiatValueManager.js
Added Jumbo token to the list of coingecko requested prices
https://mnw.atlassian.net/jira/software/projects/MYNW/boards/1?selectedIssue=MYNW-120
=> fix: MYNW-120 Fix Jumbo pricing

packages/frontend/src/components/explore/ExploreContainer.js, packages/frontend/src/components/navigation/NavLinks.js, packages/frontend/src/components/wallet/ExploreNativeBanner.js
Enable Explore page for MNW after solving img rendering issue
Resolved img rendering issue could see here: https://preflight.mynearwallet.com/explore
=> Enable Explore page for MNW

packages/frontend/README.md
Created a guide for devs to create a PR to add their wallet as an option for migration on the Near Wallet
=> docs: added guide for devs to add their wallets as options for migration

packages/frontend/README.md, packages/frontend/netlify.toml
See: https://github.com/near/near-wallet/pull/2893
In this PR instead of removing all variables and potentially breaking something, we only remove Sentry related variables
* I've also removed MixPanel token as it is deprecated (not used in near-wallet anymore)
=> config: light netlify update, remove sentry variables

packages/frontend/README.md, packages/frontend/netlify.toml
See: https://github.com/near/near-wallet/pull/2893
Doing it again, as previous commit was reverted
=> build: remove all variables from netlify.toml

packages/frontend/src/components/wallet-migration/SelectDestinationWallet.jsx, packages/frontend/src/images/finer-logo.svg
Merged #2903 - Added support for Finer Wallet only on mobile.
=> fix: Finer Wallet Mobile Support

packages/frontend/src/components/profile/Profile.js, packages/frontend/src/components/profile/hardware_devices/ConfirmDisable.js, packages/frontend/src/components/profile/two_factor/TwoFactorAuth.js, packages/frontend/src/components/wallet-migration/Disable2FA.jsx, packages/frontend/src/components/wallet-migration/utils.ts
Integrated flow for disabling 2fa for bricked accounts from user settings page.
=> feat: unbrick accounts from wallet account settings + refactoring

packages/frontend/src/components/profile/two_factor/TwoFactorAuth.js
disable users from enabling 2fa as part of the off boarding initiative
=> feat: disable 2fa enabling

packages/frontend/src/components/send/SendContainerWrapper.js, packages/frontend/src/hooks/useTokenBlacklist.js, packages/frontend/src/routes/WalletWrapper.js
Adds simplest implementation for hiding scam tokens - just a hard-coded list for now.
More flexible implementations to-be-done in next iteration
=> MNW-215: add simple FT block-list implementation 

packages/frontend/src/components/send/SendContainerWrapper.js, packages/frontend/src/hooks/useTokenBlacklist.js, packages/frontend/src/routes/WalletWrapper.js
Adds simplest implementation for hiding scam tokens - just a hard-coded list for now.
More flexible implementations to-be-done in next iteration
=> feat: add simple FT block-list implementation

packages/frontend/src/components/svg/ImportIcon.js, packages/frontend/src/components/wallet-migration/CommonComponents.jsx, packages/frontend/src/components/wallet-migration/WalletMigration.jsx, packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/CleanKeysModal.jsx, packages/frontend/src/components/wallet-migration/modals/LogoutModal/LogoutModal.jsx, packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/MigrateAccounts.jsx, packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/MigrateAccountsModal.jsx, packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/MigrationSecret.jsx, packages/frontend/src/components/wallet-migration/modals/RedirectingModal/RedirectingModal.jsx, packages/frontend/src/components/wallet-migration/modals/RotateKeysModal/ExportKeyModal.jsx, packages/frontend/src/components/wallet-migration/modals/RotateKeysModal/RotateKeysModal.jsx, packages/frontend/src/components/wallet-migration/modals/VerifyingModal/VerifyingModal.jsx, packages/frontend/src/components/wallet-migration/utils.ts, packages/frontend/src/images/wallet-migration/IconLogout.js, packages/frontend/src/translations/en.global.json
This PR contains missing steps/UIs of wallet migration.
(Excluding key clean up step)
=> Wallet Migration UI flow [WEP-175]

packages/frontend/src/components/wallet-migration/WalletMigration.jsx, packages/frontend/src/components/wallet-migration/modals/Disable2faModal/Disable2FA.jsx, packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/SelectDestinationWallet.jsx, packages/frontend/src/components/wallet-migration/modals/RotateKeysModal/RotateKeysModal.jsx
This PR contains improvements/bug fixes for wallet migration. 
1. Bug fix on situation where there is only 1 ledger account to be migrated (previously errored out)
2. Wallet list randomizing
3. Refactor/Improvements on going 2FA disable -> Rotate keys step where previously it was fetching same account info twice, causing un-necessary loading UI showing twice.
=> Wallet Migration UI minor improvements [WEP-175]

packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/SelectDestinationWallet.jsx
=> update FINER link

packages/frontend/src/components/accounts/CreateAccount.js, packages/frontend/src/components/accounts/LinkdropLanding.js, packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/SelectDestinationWallet.jsx, packages/frontend/src/components/wallet-migration/utils.ts, packages/frontend/src/translations/en.global.json
More information here: https://pagodaplatform.atlassian.net/browse/WEP-203
=> feat: Redirect linkdrop users to MNW

packages/frontend/src/components/wallet-migration/WalletMigration.jsx, packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/CleanKeysModal.jsx
This PR contains minor syntax improvements that were commented on:
[…logout step](https://github.com/near/near-wallet/pull/2996)
=> Minor Syntax improvements on wallet migration

features/flags.json
=> Revert "feat: enable WEP_PHASE_ONE in testnet"

packages/frontend/src/utils/wallet.js
ON FIRE
Linkdrops take excess of 30-40s sometimes over 1 minute to claim.
Old connection in wallet (checking for ledger on ALL accessKeys) was making 3 (yes 3) requests to getAccessKeys every time a linkdrop functionCall was being signed.
See fix for details, solution was to create basic connection that bypassed the custom signer in `wallet.ts` and use that ONLY for linkdrops.
=> fix: linkdrop connection no call to getAccessKeys

packages/frontend/src/config/buyNearConfig.js
This PR contains minor file name bug fix
=> Minor bug fix on file name inconsistency

packages/frontend/src/components/wallet-migration/modals/RotateKeysModal/ExportKeyModal.jsx
This PR contains small change on replacing button label as below:
=> Minor button label replacement

packages/frontend/src/config/environmentDefaults/development.js
Configured NODE_URL on near-cli
- https://github.com/near/near-cli/blob/aff742dae27c7afce259142263c63a30a5275276/config.js#L66
=> NODE_URL for development to be consistent with near-cli #3028

packages/frontend/src/components/Routing.js, packages/frontend/src/components/wallet-migration/WalletMigration.jsx, packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/CleanKeysModal.jsx, packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/ConfirmKeyDeletion.jsx, packages/frontend/src/translations/en.global.json
This PR contains following changes:
1. Bug fix on unable to re-open modal
2. Created two step modal to quit the account transfer
3. Implicit account text overflow on `Clean Key Step`
=> feat: wallet-migration related ux bug fix and improvements

packages/frontend/src/utils/twoFactor/twoFactorBase.js
This PR attempts to preemptively delete 2FA requests in the wallet prior to disabling 2FA. While this currently happens in `near-api-js` as part of the current disable 2FA workflow, the deletion there can be prematurely halted by attempts to delete multisig requests created too recently.
=> feat: preemptively delete 2FA keys, ignoring failures from too recent keys

packages/frontend/src/config/environmentDefaults/mainnet.js, packages/frontend/src/config/environmentDefaults/mainnet_STAGING.js, packages/frontend/src/config/environmentDefaults/testnet.js, packages/frontend/src/config/environmentDefaults/testnet_STAGING.js, packages/frontend/src/utils/twoFactor/twoFactorBase.js
#3036 addresses issue in earlier release
=> 2022-04-06 Release

.github/workflows/bundle-and-deploy.yml, .github/workflows/deploy-master.yml, .github/workflows/deploy-stable.yml
Actions to deploy to GCP buckets
=> ci: GCP deployment actions

packages/frontend/src/components/wallet-migration/modals/RotateKeysModal/RotateKeysModal.jsx
This PR contains removal of `export key step` on transfer wizard. 
After discussion with the rest of the team, we all agreed that this step doesn't provide realistic value and decided to remove the step to simplify the process
=> Remove export key step on transfer wizard

packages/frontend/src/hooks/useTokenBlacklist.js
This PR adds an FT blacklist entry for the spam token `youwon400neartoclaimyourgainwwwlotte.laboratory.jumpfinance.near` on wallet.near.org.
=> feat: add FT to blacklist

packages/frontend/src/components/accounts/ledger/LedgerConnectModal/views/LedgerConnectionModal.js, packages/frontend/src/components/accounts/ledger/SignInLedgerViews/Authorize.js, packages/frontend/src/translations/en.global.json, packages/frontend/src/translations/it.global.json, packages/frontend/src/translations/kr.global.json, packages/frontend/src/translations/pt.global.json, packages/frontend/src/translations/ru.global.json, packages/frontend/src/translations/tr.global.json, packages/frontend/src/translations/ua.global.json, packages/frontend/src/translations/vi.global.json, packages/frontend/src/translations/zh-hans.global.json, packages/frontend/src/translations/zh-hant.global.json
Added alert banner when connecting ledger.
=> Added ledger disclaimer banner with translations

packages/frontend/src/routes/TransferWizardWrapper.js
This PR contains label/content update on transfer wizard static page.
=> Minor update on contents of transfer wizard static page

packages/frontend/src/translations/en.global.json
This PR contains minor update on wallet migration message, including a new official announcement that describes about the wallet migration in general. 
Which links to:
https://near.org/blog/embracing-decentralization-whats-next-for-the-near-wallet
=> Minor update on wallet migration warning message

features/flags.json, packages/frontend/src/translations/en.global.json
=> Release 2023-07-14

packages/frontend/src/translations/ru.global.json
Reverts near/near-wallet#3085 in favor of #3084
=> Revert "Minor translation fix related to transfer wizard in RU"

packages/frontend/src/translations/ru.global.json
Fixed ru translation of migration message (origin from English version)
=> fix: ru translation of migration message

packages/frontend/package.json, packages/frontend/src/components/wallet-migration/modals/WalletSelectorModal/WalletSelectorExportContext.jsx, yarn.lock
Thanks to Sender Wallet team, we now can list Sender Wallet as part of Transfer Wizard.
I have tested on testnet environment and it was LGTM. 
Will proceed to test on staging environment once it gets released.
=> Add Sender Wallet to transfer wizard

packages/frontend/src/components/wallet-migration/modals/WalletSelectorModal/WalletSelectorExportContext.jsx
This PR contains changes on the order list of wallets on Transfer Wizard as below:
=> Convert the transfer wizard wallet list to static order

packages/frontend/src/translations/en.global.json
Addresses https://github.com/near/wallet-experience/issues/5
=> Update wallet deprecation date in English

packages/frontend/src/routes/TransferWizardWrapper.js
This PR contains the transfer wizard static page update.
- Removing key rotation and deletion steps as we no longer have them on the process
- Minor language update to remove the part that mention about key rotation/deletions
=> Minor Transfer wizard static page
