near/near-wallet

- src/middleware/index.js
Tracking a few key actions as GA events so we can build better funnels than what Google gives us out of the box
> Add middleware to track key user actions in google analytics

- src/components/responsive/DesktopPopup.js
Reverts nearprotocol/near-wallet#260
Popup doesn't look right in Safari
> Revert "Update DesktopPopup.js"

- src/components/GlobalStyle.js
Anything lower than 16px will cause the mobile browser to zoom in, resulting in bad UX.
> Input font size: increase to 16px

- src/components/accounts/AccountFormAccountId.js
- src/components/accounts/CreateAccountForm.js
- src/components/send-money/SendMoneyFirstStep.js
@vgrichina do we need any additional change for it (#311)? For example, will `getAccount` wallet function work with a subdomain in accountId?
> Allow to add subdomain to accountId on Send Money page

- src/reducers/account/index.js
@vgrichina The thing is that `setupRecoveryMessage` action contains another action, in this case `getAccessKeys`, so after `getAccessKeys` action is completed (and before `setupRecoveryMessage` is completed) the `loaderReducer` did set `formLoader` state to `false`, so the button was available. 
I added a stack to `loaderReducer` that will store all actions that started, so we will wait with setting `formLoader` to `false` till all actions are completed.
@kcole16  The same problem was on Setup Recovery Phrase page, so it's fixed with this change as well.
> Fix button feedback delayed on Protect your Account and Setup Recovery Phrase pages

- src/components/profile/ProfileQRCode.js
* No need for the `&`, as root declaration will already be for the component-being-styled
* `h2` removed from markup in 17e102d772ac2c628a026f8a6bafd976a75e916f, we no longer need style rules for it
* grammar: "your phone's camera", we need an apostrophe for the possessive
> Clean ProfileQRCode: simplify styles; fix grammar

- src/actions/account.js
In 1b0d3a1d70363e7578a053c737c3aebc7326d3, `loadAccount` stopped using the `history` argument. In 57e22bea8abc978df0c7d4b7bd230ce3558ca2d5, it stopped paying attention to the second argument passed in altogether.
actions/account.js is free to stop sending a second argument
Note that my editor is also configured to strip trailing whitespace from lines, which adds some noise to this change
> clean up actions: loadAccount has no 2nd arg

- src/components/responsive/DesktopPopup.js
- src/components/responsive/PopupMenuTrigger.js
Previously we always showed a spinner if there's no account info. Now we only show spinner if it's actually loading
Issue first mentioned [here](https://github.com/nearprotocol/near-wallet/pull/359#issuecomment-582189411)
> Navbar: only show account info if it exists

- src/components/common/Balance.js
I added `FRAC_DIGITS` so it will be easy to change number of fractional digits in the future.
`formatWithCommas` is copied from nearlib utils, it can be removed if we can export this function from nearlib.
> Display yoctoN in title tag if amount is <=0.0001 (#290)

- src/actions/account.js
- src/components/Routing.js
- src/components/profile/Profile.js
- src/components/responsive/DesktopPopup.js
- src/components/responsive/MobileView.js
- src/hooks/allAccounts.js
- src/reducers/allAccounts.js
- src/reducers/index.js
Previously, this app would only show you your own profile at `/profile`
This changes the route to `/your-username`, and allows showing anyone else's profile at this route as well
If viewing your own profile, data is loaded immediately from the redux store, which is cached in localStorage. If viewing someone else's, data is fetched directly in the component, since no other components use this data currently and we do not need to pollute the global state with it.
> Add support for showing generic profiles

- src/components/common/Balance.js
This fixes TX signing from breaking when value is below threshold. https://github.com/nearprotocol/near-wallet/commit/da2ed7cc92975ddef08231e7e1a685cb3ae6ba37
> Sign TX: convert tx value to string before formatting

- src/actions/account.js
- src/components/responsive/GlobalAlert.js
Re-directing user back to app at the same time as we show the success alert is confusing since user doesn't have time to read/understand the alert. Removing it if there's a re-direct url.
> Login to app: don't show GlobalAlert if there's a success url

- src/actions/account.js
- src/translations/en.global.json
- src/utils/wallet.js
`validateCode` was only used by `setupAccountRecovery` and `recoverAccount`, which are no longer used
> refactor: rm obsolete validateCode and others

- src/utils/copyText.js
Chrome, Firefox, IE: `clipboard.writeText`
Safari: `document.execCommand('copy');`
> Add fallback 'copy to clipboard' method

- src/translations/en.global.json
Updated the seed phrase recovery labels (`Choose a Username` -> `Username`, `Seed Phrase` -> `Seed Phrase (12 words)`) and placeholder.
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/522"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/149d801483ef9c9b5426a13725eacfc2f6861a7e.svg" /></a>
> Update seed phrase recovery copy

- src/components/accounts/AccountFormAccountId.js
- src/translations/en.global.json
- src/utils/wallet.js
The modal that popped up did not match the suffix shown in the account creation form. This makes them match, and moves the strings of text to the translations file so we don't miss them when translating the interface to new languages.
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/535"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/dcf633c7aa88f03c176d83c8a08b47980f64e8e2.svg" /></a>
> Make all info about TLA use env var

- src/utils/wallet.js
https://github.com/near/near-api-js/commit/a69016a616a8a99052059adbb323c2422ab27200 needed to avoid troubles with keys after near-api-js rename
> Pass explicit storage prefix for BrowserLocalStorageKeyStore

- package.json
- src/index.js
- src/middleware/index.js
- yarn.lock
We need to start tracking errors as the goal is stabilize as much as possible for mainnet. Some flows anecdotally have a chance to fail with error and get stuck (e.g. Sasha got stuck creating account).
Sentry chosen because it has decent open-source policy: https://sentry.io/_/open-source/  and we can self-host it if needed.
Fixes https://github.com/near/near-wallet/issues/506
WIP: not configured data scrubbing yet
> Integrate Sentry for error reporting

- src/actions/account.js
- src/actions/transactions.js
- src/components/dashboard/ActionsList.js
- src/components/dashboard/DashboardActivity.js
- src/components/dashboard/DashboardDetail.js
- src/reducers/account/index.js
- src/reducers/index.js
- src/reducers/transactions/index.js
- src/utils/explorer-api.js
Thanks to this change, the transactions list will be cleared (before fetching a new list) if the user will create a new account, recover account, or switch account.
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/541"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/345b8ebbffca3f3c04927f9c61b74fae2c473b61.svg" /></a>
> Clear transactions for new accountId (#519)

- src/components/accounts/RecoverAccountSeedPhraseForm.js
We've had reports of users encountering "Please match the requested format" when trying to recover with seed phrase. Reproducibility is unpredictable but I've encountered it myself sometimes when copying phrase from Apple notes app.
`pattern='[a-zA-Z ]*'`
https://github.com/near/near-wallet/issues/653
> phrase recovery: remove input regex

- src/components/profile/Profile.js
- src/components/profile/Recovery/ActiveMethod.js
- src/components/profile/Recovery/InactiveMethod.js
- src/components/profile/Recovery/RecoveryContainer.js
- src/components/profile/Recovery/RecoveryMethod.js
- src/reducers/account/index.js
- src/translations/en.global.json
- src/utils/wallet.js
- Keep order of recovery methods fixed
- Refactor `RecoveryContainer` to use the `useRecoveryMethods` hook
- Replace Snackbar with GlobalAlert for recovery link resend success/failure to keep UX consistent with initial recovery method setup.
- Show Ledger module on profile only if you're logged in to account
cc @corwinharrell
> keep order of recovery methods fixed on profile

- src/components/profile/Recovery/RecoveryContainer.js
Bug: List of recovery methods was showing 2FA methods too. Updated filter to exclude any method that doesn't have a publicKey.
> remove 2fa methods from recovery methods list

- src/actions/account.js
- src/components/Routing.js
- src/components/accounts/AccountFormAccountId.js
- src/components/accounts/AccountFormContainer.js
- src/components/accounts/CreateAccount.js
- src/components/accounts/CreateAccountForm.js
- src/reducers/account/index.js
- src/translations/en.global.json
- src/utils/localStorage.js
- src/utils/wallet.js
This is the second attempt for #349 changes, with a different flow. 
With these changes when the account exists in local storage but does not exist in the blockchain, we will clear the account (only this one) from local storage. Next:
1. If the user has another account we will load the account, leave him on the same page and show GlobalAlert with info. 
2. If the user does not have another account he will be redirected to Create Account and we will show the same globalAlert.
#349 can be closed.
<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/443"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/near-wallet.git/198ea3838fc5e55710926d19701780a7514e3d57.svg" /></a>
> Fix account creation when the network is slow, with flow changes

- README.md
removed mention to https://wallet.nearprotocol.com/ -- wallet.nearprotocol.com is deprecated
The site and then the local storage can be https://wallet.testnet.near.org/ or https://wallet.near.org/ or others
> (fix) Update README.md - remove mention to https://wallet.nearprotocol.com/ 

- src/actions/account.js
- src/components/Routing.js
- src/components/accounts/two_factor/TwoFactorVerifyModal.js
- src/translations/en.global.json
- src/utils/twoFactor.js
- src/utils/wallet.js
This PR fixes the 2FA modal that was previously reporting success and not throwing errors properly.
It will now reject in the modal promise with the errors from contract helperand for no code / incorrect code and also reject with error if the user cancels the modal.
@Patrick1904 you may want to dive in and customize the error messaging in the UI.
See code changes for where/how errors are being thrown and potential spots to customize by throwing your own WalletError.
> 2FA Modal Promise Should Reject With Error

- src/components/accounts/SetupSeedPhrase.js
- src/components/accounts/SetupSeedPhraseForm.js
- src/components/accounts/recovery_setup/SetupRecoveryMethod.js
- src/components/profile/Recovery/InactiveMethod.js
PR fixes adding seed phrase as a "second" recovery option.
Issue: "start over" button flips bit on isNew to true so wallet thinks it's setting up a new account.
> Fixes setup seed phrase - start over turns into new account creation

- src/actions/account.js
- src/components/accounts/ledger/SignInLedger.js
- src/reducers/ledger/index.js
- src/translations/en.global.json
This fixes the issue when `ledger confirm action modal` was displayed while creating a new account if current account had Ledger recovery enabled.
> Fix displaying modal if a new account is being created with email, phone or seed phrase recovery

- src/components/profile/Recovery/RecoveryContainer.js
Verify that public key for a recovery method exists on chain before displaying the method as 'active' on profile
> recovery methods: verify that public key exists on account

- src/actions/account.js
- src/utils/wallet.js
Account created through linkdrop can be fully lost if minor error happens during recovery setup: account still gets created, but users often don't keep original seed phrase.
This change makes sure that in such case there is at least key in localStorage.
> Hotfix: mitigate ways to lose account

- src/components/profile/Recovery/RecoveryContainer.js
Error is sometimes thrown when re-directing to profile post creating an account. Now checking that `fullAccessKeys` exists before mapping.
> fix referencing full access keys

- src/utils/wallet.js
Add support for the lockup contract naming convention <account_name_without_suffix>.lockup.<network_suffix>
> Update lockup contract support for new naming convention

- src/components/accounts/two_factor/TwoFactorVerifyModal.js
This fixes the issue with the 2FA modal erroring on close and subsequently the staking modal not closing as a result.
> hot fix: twoFactorVerifyModal not returning success with empty return value from rpc

- src/actions/account.js
- src/components/accounts/two_factor/EnableTwoFactor.js
- src/utils/twoFactor.js
- src/utils/wallet.js
This fixes enabling of 2fa accounts after we merged the 2fa refactor that depends on new near-api-js AccountMultisig
> [hot fix] 2fa enabling after 2fa refactor

- src/components/staking/components/AmountInput.js
- src/components/staking/components/Stake.js
- src/utils/staking.js
1. Cap the min displayed "Available lockup balance" at 0.001
2. Allow user to type in exactly what "Available Balance" says and still have staking succeed
3. Included 35N strict reserve vs. storage calculation
Fix for #1006
> Fix staking max

- src/utils/twoFactor.js
- src/utils/wallet.js
This doesn't catch RPC but instead requires accountId to be passed and checks if it's valid before calling `.state()`
> better fix for 2fa isEnabled

- src/components/Routing.js
- src/components/accounts/SetupImplicit.js
- src/components/accounts/SetupSeedPhraseForm.js
- src/components/navigation/Navigation.js
- src/translations/en.global.json
- src/utils/staking.js
PR creates a new route `/create-implicit` for creating implicit accounts
1. copy seed phrase
2. verify
3. copy accountId
4. fund from somewhere
5. click check balance and redirected to `/recover-with-link/:accountId/:seedPhrase`
Some minor changes to other components were necessary to make UI work
- SeedPhraseForm
- Navigation
TODO
Uses localStorage to store seedPhrase and accountId, which should be cleared after user is recovered into wallet successfully.
> Add /create-implicit route and page to create implicit accounts with seed phrase

- src/components/profile/Profile.js
Verify hash in combination with contract helper before showing 2fa as enabled. One of my accounts had a 2fa entry in contract helper, but there was no contract deployed on account, which lead to false positive.
> Verify 2fa hash before showing 2fa as enabled

- src/components/staking/StakingContainer.js
- src/components/staking/components/Validator.js
Since we do not call `unselect_staking_pool` until user stakes with a new validator, we need to check if the user is staking. The `currentValidators` array should be empty if there's no balance.
> Lockup staking: fix stakeAllowed flag

- src/utils/account-with-lockup.js
- src/utils/staking.js
For non-lockup accounts, we were only deducting 1N from available balance to stake. This deducts 2N from available balance, so that users see the same 'Available Balance' on the staking dashboard and /profile
> Deduct 2N from available staking balance to align with profile page

- src/components/navigation/NavLinks.js
Hey team!
I started using the wallet and noticed that the "receive" icon points "outside", and this is kinda counter-intuitive. I suggest rotating it by `90deg` instead of `180deg` (so the arrow would point "down").
Before:
After:
Let me know what you think!
> Turn "Receive" arrow icon into a "down arrow" instead of a "left arrow"

- src/actions/account.js
- src/components/accounts/ledger/LedgerSignInModal.js
- src/components/accounts/ledger/SignInLedger.js
- src/reducers/ledger/index.js
- src/translations/en.global.json
- src/utils/wallet.js
Context: whoever added 2FA after Ledger (e.g. by importing account using other recovery method) has troubles recovering any accounts connected to the same Ledger (so this is relatively urgent fix for people in such situation).
As a drive-by it also allows to press "Reject" for some accounts and skip them (seems like more desired behavior than restarting whole process).
Known issues:
- missing translations
- need design for Error/Rejected state @corwinharrell 
- need to distinguish Error/Rejected (just shows Error now)
- account list doesn't scroll after rejection (not sure whether regression here)
- there seem to be Ledger UI issues which weren't introduced in this PR https://github.com/near/near-wallet/issues/1124
> Allow importing remaining Ledger accounts if one fails

- src/utils/wallet.js
For recovery methods that DO NOT have a `publicKey`, check that the methods `confirm` flag is `true`
> Fix 2fa not showing as active on profile

- src/components/staking/components/Validators.js
- src/utils/staking.js
pulls more validators (historic) from GH list:
`https://raw.githubusercontent.com/frol/near-validators-scoreboard/scoreboard-${networkId}/validators_scoreboard.json`
streamlines validator list to currentValidators only when user is staking
> adding gh validators to validators list

- src/utils/account-with-lockup.js
- src/utils/staking.js
call refresh_staking_pool_balance and get liquid before throwing not enough tokens error
for users unstaking their rewards:
https://github.com/near/core-contracts/tree/master/lockup#refresh-the-current-total-balance-on-the-staking-pool
> add refresh_staking_pool_balance call

- src/actions/account.js
- src/components/accounts/two_factor/EnableTwoFactor.js
- src/utils/wallet.js
Changes:
1. Added a 'Skip' button to `/enable-two-factor`
2. Require that user has at least 200N available balance before prompting 2FA setup
> Allow skipping 2FA setup

- src/actions/account.js
- src/components/profile/Profile.js
- src/utils/wallet.js
fixes when user doesn't confirm 2fa their 2fa method will disappear from profile
now it won't
> small update to filter out 2fa methods from recoveryMethods

- src/actions/account.js
- src/utils/twoFactor.js
There was a mismatch between twoFactor.js and Account2FA from near-api-js.
Discovered via Sentry this morning.
Reduced code. e2e tested branch for resending 2fa code:
- deploying 2fa account
- sending 2fa tx
> hotfix for resend 2fa codes

- src/components/staking/StakingContainer.js
- src/components/staking/components/ValidatorBox.js
- src/reducers/account/index.js
- src/translations/en.global.json
We now show any potential error from trying to stake, unstake, and withdraw on the UI using the GlobalAlert. Fixes a common case where users don't have enough tokens to cover the TX cost.
> Show UI error for stake, unstake, withdraw

- src/components/common/styled/Container.css.js
- src/components/send/SendContainer.js
Fixes scenario where user with 2FA is on `/send-money` -> enters amount and receiver -> clicks 'submit' -> clicks 'confirm' on the confirmation modal -> 2FA modal shows up and user hits 'enter' on their keyboard without entering the 2FA code -> this triggers another 'send' request
> Send bug: do not allow to send when formLoader is true

- src/actions/account.js
- src/components/accounts/AccountFormAccountId.js
- src/components/accounts/CreateAccount.js
- src/components/accounts/CreateAccountForm.js
- src/components/accounts/ledger/LedgerSignInModal.js
- src/components/accounts/ledger/SignInLedger.js
- src/components/send/SendContainer.js
- src/reducers/account/index.js
It is something that makes it hard to have consistent state for `formLoader` and so breaking all logic to disable forms, etc
> Remove setFormLoader from everywhere

- src/components/accounts/EnterVerificationCode.js
- src/components/accounts/SetupSeedPhrase.js
- src/components/accounts/SetupSeedPhraseVerify.js
- src/components/accounts/recovery_setup/SetupRecoveryMethod.js
- src/components/accounts/two_factor/EnableTwoFactor.js
- src/components/accounts/two_factor/TwoFactorVerifyModal.js
- src/components/send/SendContainer.js
- src/components/staking/components/StakingAction.js
- src/reducers/account/index.js
- Guard against attempts to 're-submit' action related to: send, stake, recovery, 2FA. Any click or key press (enter).
- Guard against submitting incomplete forms or while things are loading
- Clean up and use dispatch vs history.push
- Add missing await(s)
- Show globalAlert for incorrect code during 2FA setup
Note: most fixes above are for **Safari** browser.
> Keyboard related fixes to Send, Stake, Recovery, 2FA

- src/components/staking/components/Validator.js
Protects against attempt to initiate withdrawal while withdrawal is already in progress (by pressing enter)
> Validator page: disable onKeyDown while loading and cleanup

- src/translations/en.global.json
Epochs are now ~13 hours. Unstaked tokens become available for withdrawal after: 36-48hrs -> **52-65hrs** (4 epochs)
> Update epoch duration

- src/components/dashboard/ActionsList.js
- src/translations/en.global.json
- src/utils/explorer-api.js
Uses a new endpoint from indexer to fix issues with activity feed not showing 2FA and other contract runtime actions (e.g. transfers that a contract does to your account)
CH PR:
https://github.com/near/near-contract-helper/pull/303
**Relies on: REACT_APP_ACCOUNT_HELPER_URL="https://near-contract-helper-2fa.onrender.com" until PR is merged.**
> Fix Activity Feed - uses new CH endpoint

- src/utils/staking.js
- src/utils/wallet.js
Updated the rewards calc.
Additional:
Access key amount bumped to the default from our ENV vars, 0.1 is too low for staking txs
> hotfix: total - deposits vs. staked - deposits

- src/components/staking/components/ValidatorBox.js
- src/components/staking/components/Validators.js
- src/utils/staking.js
bug: the UI was filtering validators out if not current or next status
bug: the UI was filtering out validators with fee: 0
fix: includes all validators in /Validators component list, shows (active) or (inactive) status
> show all validators with active / inactive status

- src/translations/ru.global.json
- src/translations/zh-hans.global.json
- src/translations/zh-hant.global.json
This PR fixes an error that occurs during account creation (funding flow), once the 'account funded' modal shows. The error only occurs if the selected language in the Wallet is Chinese or Russian.
To test this fix:
1. Switch language in the Wallet to either Chinese or Russian
2. Create a new account that requires funding
3. Successfully create and fund the account without any errors
> Fix missing translation bug

- src/components/Routing.js
@Patrick1904 This is the fix.
`onMissingTranslation` was removed  in https://github.com/near/near-wallet/commit/8581a373f6db9e0dddac1875b7b81aa92ab4fd3d. Maybe ask @icerove before merge?
> Add back fallback for missing translations

- src/components/navigation/DesktopContainer.js
- src/index.html
Point 'HELP' button to `https://nearhelp.zendesk.com/` instead of Discord.
> Point 'HELP' button to Zendesk page

- src/actions/account.js
- src/components/profile/Profile.js
- src/utils/twoFactor.js
**Current issue:**
Refresh the browser on the `/profile` page and notice that you're not able to enable 2FA - it says not enough funds
**Acceptance criteria:**
You can enable 2FA after refreshing the browser while on the `/profile` page - assuming you have enough funds in 'available balance' and do not have Ledger enabled.
> Fix 2fa check for Profile page refresh

- src/components/accounts/RecoverWithLink.js
The 'link expired' screen was showing while the account was being recovered.
> Recover with link: Fix error case

- src/components/staking/components/StakeConfirmModal.js
- src/components/staking/components/Validator.js
Changes for withdrawing from staking pool:
1. Fix bug that causes stake withdrawal modal to show after withdrawal is successful
2. Remove `onKeyDown` listener as there's no `form` part of the stake withdrawal flow
> Fix withdraw stake modal

- package.json
- yarn.lock
This update should improve wallet performance and reliability.
But please test and watch out if anything goes wrong.
> Update to near-api-js 0.37.0

- src/utils/wallet.js
Basically implicit account is only deleted in case when it would be re-created intact on repeated transfer.
> Don't delete funding account if it has changes to public keys

- src/components/send/SendContainer.js
Fixes issue with 'submit' button being disabled when going to `/send-money` with account ID in the url.
To test:
1. Go to `/send-money/aValidAccountId`
2. Verify that the 'submit' button is enabled once you have entered a valid amount
> Fix validate account ID from URL

- src/reducers/sign.js
Added an initial array value for `gasLimit` reducer in `sign.js`
Fixes #1544
> Fix array error when signing transactions

- src/components/wallet/TokenBox.js
Changes:
1. Show as much as possible of the contract/account string before applying ellipsis
2. Make the contract/account clickable -> explorer
> Fungible token: link to explorer

- src/components/sign/Sign.js
Fixes #1588 
When no `meta` is provided when signing with the wallet, don't add `meta=undefined` as a query param when returning to the application.
> no undefined meta in callbackUrl

- src/actions/account.js
**Changes:**
1. Add support for optional `redirectUrl`
2. Add `accountId` as url param to `redirectUrl`
**Example:**
`https://wallet.near.org/create?redirectUrl=https://berryclub.io/`
After account creation --> `https://berryclub.io/?accountId=johndoe.near`
**W/ linkdrop example:**
`https://wallet.near.org/create/near/VGmU9e2cEgE8PHysrBdjeJkbzvvFtBYT1UgEmDHTFTp81gnHSdKZCVyVpV5PwjYT6FX7Znd731HCvSpVnJJmgnx?redirectUrl=https://berryclub.io/`
After account creation --> `https://berryclub.io/?accountId=johndoe.near`
> Add support for redirectUrl on /create route

- src/components/sign/SignTransferReady.js
- src/components/staking/components/BalanceBreakdown.js
- src/translations/en.global.json
**Changes:**
1. on `/sign`: when transfer is requested, show 'Available to transfer' and clickable balance breakdown.
**To test:**
1. Create or recover a testnet account on https://near-wallet-pr-1671.onrender.com 
2. Go to https://near-examples.github.io/guest-book/ and click 'Log in'
3. Edit the login URL by replacing https://wallet.testnet.near.org with https://near-wallet-pr-1671.onrender.com
4. Approve the app login request
5. Now sign a message with a donation
6. Edit the sign URL by replacing https://wallet.testnet.near.org with https://near-wallet-pr-1671.onrender.com
7. Observe the balance dropdown
> Sign transfer: add balance breakdown

- src/components/login/Login.js
- src/components/login/LoginForm.js
- src/translations/en.global.json
When app doesn't provide contract and key:
1. Show '{App} is asking for your Account ID.'
2. Hide 'More information' button
For testing, [app.ref.finance](https://app.ref.finance/) is a good example.
> App login: fix app login when only asking for users Account ID

- src/actions/account.js
This allows method names to be passed via the URL to restrict an access keys usage to a subset of methods on a smart contract.
Associated `near-api-js` PR: https://github.com/near/near-api-js/pull/578
> Add methodNames to URL for signin

- package.json
- yarn.lock
We cannot import account into Wallet on testnet or login any DApp on testnet now. Developers from community keep reporting this issue. 
error message
```
adding full access key ed25519:DDXd.....
instrument.ts:129 TypeError: Cannot read property 'map' of undefined
at p.<anonymous> (account-with-lockup.js:29)
at f (runtime.js:63)
at Generator._invoke (runtime.js:293)
at Generator.next (runtime.js:118)
at l (account-with-lockup.js:234)
at o (account-with-lockup.js:234)
```
This is caused by near-api-js upgraded to **0.41.0** which introduced some compatibility issues.
The account cannot be imported because it failed to **addKey** via `near-api-js`
> rollback near-api-js upgrade

- src/actions/account.js
Important since `createAccountFunded` contract helper route will throw errors for reCaptcha related errors before the NEAR account has been created.
Prior to this change, no matter what caused an error to be thrown from the `createAccount()` call, we assumed that it was after the NEAR account was created and that it would be sane to redirect the user to the `recovery-seed-phrase` route to let them import the account to the wallet.
Without it, errored responses from the createFundedAccount contract-helper involving reCaptcha would be a fatal onboarding error requiring the user restart the create account process from the beginning.
> 1659 - Only redirect to `/recover-seed-phrase` if NEAR account was successfully created

- src/actions/account.js
- src/components/GlobalStyle.js
- src/components/common/Balance.js
- src/components/navigation/DesktopContainer.js
- src/components/navigation/DesktopMenu.js
- src/components/navigation/MobileContainer.js
- src/components/navigation/Navigation.js
- src/components/navigation/UserAccounts.js
- src/reducers/account/index.js
- src/reducers/status/index.js
- src/translations/en.global.json
1. Request is starting when the submenu is opened.
2. Balance for accounts is fetched sequentially, to make it a bit lighter.
3. It needed some additional work including `localAlert` mechanism and `mainLoader` - because we rely on `mainLoader` for some local actions, I think that in future works we should avoid using `mainLoader` and instead use `actionsPending` for specific actions. `mainLoader` should be used if we decide to add main loader to Wallet.
4. Also added `Refresh` button for every account balance, it might be handy for users if, for example, you want to check if balance changed without switching account.
Please try to open the submenu, and send money quickly. It works well for 7 accounts or less, but if you have more, you would need to wait longer for the transfer to finish. …
> Add balance to every account in Switch account section on the top nav (#1496)

- src/actions/account.js
- src/components/Recaptcha.js
- src/components/accounts/SetupSeedPhrase.js
- src/components/accounts/ledger/SetupLedger.js
- src/components/accounts/recovery_setup/SetupRecoveryMethod.js
- src/utils/wallet.js
Closes #1779
Adds new Mixpanel events throughout the funded account flow
See #1779 for the things we can now track via Mixpanel events.
Note: I moved `setupRecoveryMessageNewAccount()` out of `wallet.js` because I wanted to add Mixpanel tracking to this logic, but didn't want to leak Mixpanel awareness into the code in `wallet.js`.  It also was a bit of a mis-fit for `wallet.js` because it was one of the few places there that used our `store.dispatch()` method directly to dispatch a bunch of sub-actions.  Incidentally, this had caused me to add handling of `NotEnoughBalance` errors during account creation inside `wallet.js` _only for this one case_ where the other account creation flows had the logic in the UI components -- so by moving this code out of the actions, we avoided adding …
> Add Mixpanel events for funded account flow

- src/actions/nft.js
Reverts near/near-wallet#1844
Reverting this as it causes issues with NFTs from Pluminite. Will have to be fixed.
> Revert "Fix limit must number by NEP-181"

- src/actions/account.js
- src/components/accounts/LinkdropLanding.js
- src/utils/wallet.js
Resolves: #1827
Similar to #1641 which is designed specific for new users, add url redirect support after an existing user claimed the linkdroip.
> Add linkdrop redirect for existing users

- src/components/sign/SignTransferReady.js
Changes:
1. On the `/sign` route: Only disable the 'Allow' button once the account balance has finished loading and `insufficientFunds` is confirmed in order to speed up the UX when the user first lands on the page.
2. Also removing the `isMonetaryTransaction` flag as it's being determined while setting `insufficientFunds` anyway.
> TX sign: disable 'Allow' button only if confirmed insufficient funds

- .github/dependabot.yml
Disables automatic creation of non-security related package version update PRs 
**- Security vulnerabilities will still result in PRs being created.**
- This is ensured by updating the dependabot.yml NPM configuration to target the `dump` branch.  Per this documentation, this ensures that the overridden configuration of 0 PRs max will not change the defaults that the security updates use: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/customizing-dependency-updates#impact-of-configuration-changes-on-security-updates
- Currently, since dependabot creates PRs for stuff like patch releases of our dependencies, we see a constant stream of PRs opened for our dependent packages (10 at a time by our existing configuration) which …
> Stop dependabot from spamming PRs about minor changes to our dependencies

- src/components/Routing.js
- src/utils/getBrowserLocale.js
Closes https://github.com/near/near-wallet/issues/704
To improve the UX of wallet for non-English users, the wallet should automatically detect the browser language, and switch to the user defined browser language. 
The browser language detection works for all the languages except Tranditional Chinese `zh-hant`, because the browser locale retrieved from `window.navigator.languages` are `zh-TW` or `zh-HK` for the Traditional Chinese users, which don't match with the locale code `zh-hant` we used in the wallet app. All the `zh-XX` (including `zh-CN`, `zh-TW`, `zh-HK`) codes now will be matched to `zh-hans` by default in the current design. 
To fix this issue, we added some special handing for `zh-TW` or `zh-HK` to return `zh-hant` in …
> Automatically detect browser language

- src/actions/account.js
- src/components/accounts/CreateAccount.js
- src/components/accounts/LinkdropLanding.js
- src/components/accounts/RecoverAccountSeedPhrase.js
- src/components/common/FormButton.js
This PR fixes https://github.com/near/near-wallet/issues/1875  The redirect doesn't work if a user import a new account and then claim the linkdrop. 
To fix the issue, we need to: 
1. ensure the `redirectUrl` parameter (or the state that saves this parameter) is not lost when jumping back from the `recover-account` and `recover-seed-phrase` pages;
2. the `redirectUrl` parameter was saved into state correctly, so the redirection could happen successfully
> Fix linkdrop redirect after recover account

- ci/ParcelBundler.js
SSL problems :(. This will leave it enabled for staging/mainnet but disable it only for testnet for now.
> Disable Cloudflare for testnet

- src/translations/zh-hans.global.json
- src/translations/zh-hant.global.json
The Chinese translation of claiming linkdrop with existing account is inaccurate. 
Fix this with the more accurate translation.
> i18n: Fix claim linkdrop Chinese translation

- src/utils/wallet.js
Fixes: #1919 
Now claim linkdrop is extremely slow (>60s) in Mainnet Wallet.
The root cause is that for signing transaction in wallet, now we'll first `getLedgerKey()` which will call `getAccessKeys()` and then filter out the ledger key.  This is OK for most accounts, but for acounts with thousands of keys such as `near` or `testtnet`, it impacts the performance significantly. 
https://github.com/near/near-wallet/blob/b58683fd7032b26e38a28a6385dc6f0ebf47068f/src/utils/wallet.js#L99-L120 
1. We don't need `getLedgerKey()` for some accounts such as the root account: `testnet`, `near`, etc.
2. We should make `getLedgerKey()` more efficient if possible, by removing unnecessary query of all access keys, or add more caches to avoid duplicate requests. 
Here, due to the urgency of the fixing the …
> Remove unnecessary queries of account access keys via RPC

- package.json
- src/actions/account.js
- src/components/navigation/DesktopContainer.js
- src/components/navigation/DesktopMenu.js
- src/components/navigation/MobileContainer.js
- src/components/navigation/Navigation.js
- src/components/navigation/UserAccounts.js
- src/components/send/SendContainerWrapper.js
- src/components/send/components/ReceiverInputWithLabel.js
- src/components/wallet/Wallet.js
- src/hooks/fungibleTokensIncludingNEAR.js
- src/reducers/account/index.js
- src/reducers/sign.js
- src/reducers/status/index.js
- src/reducers/transactions/index.js
- src/translations/en.global.json
- src/utils/wallet.js
- yarn.lock
1. Adds a row for NEAR tokens to the main `tokens` list on the dashboard page
- The `balance` value here will be the _total_ balance (same as we show in large text at the top of the dashboard)
- `Sendable balance` in the token selection list inside of the `send` flow remains un-changed
- This is facilitated via the `useFungibleTokensIncludingNear` hook. In the future we should probably get NEAR _into the tokens reducer_, but that was not in-scope for shipping today! :)
2. Fixed our account input field constantly throwing errors to the console during normal operation
- If I type slower than 500ms between each key, I was generating un-caught errors for _every single keystroke_ up until I finished typing `.near` on the end of the account name
Now we won't be sending thousands and thousands …
> Show NEAR tokens in the token list on the main dashboard

- src/components/send/SendContainerV2.js
- src/components/send/SendContainerWrapper.js
- src/components/send/components/InputAccountId.js
- src/components/send/components/ReceiverInputWithLabel.js
- src/components/send/components/views/EnterReceiver.js
Per the title, since we round up for displaying the amount to the user, we need to handle this case specially in two ways:
1. To avoid validation failing because the amount we show the user is technically more than the amount of available balance
2. To ensure that we do send the _entire_ balance when someone actually submits the transaction and we don't leave token dust behind :)
> Add `isMaxAmount` to handle edge cases around sending the entire balance of a token

- src/index.html
Fixes: #1933
Loading JS and CSS from Cloudflare workers failed when using Huawei / QQ Browsers, etc. 
Force `strict-origin-when-cross-origin` in html to change the referrer url to origin only to resolve the issue.
> Add `strict-origin-when-cross-origin` meta to fix the `referer` issue for Huawei browsers, etc.

- src/actions/nft.js
- src/components/send/SendContainerWrapper.js
- src/services/FungibleTokens.js
- src/utils/wallet.js
1. Refactored fungibleTokensService to no longer have a `this.account` property that we needed to keep in sync with the rest of the wallet UI/systems
- removed fungibleTokensService.signAndSendTransaction() function since it was superfluous post-refactor
2. Moved some methods to be static methods on the FungibleTokens class since they are purely viewFunction calls
- Using a statically created account object for `viewFunction` calls since they aren't actually signed
3. Removed spammy and not useful console.logs inside the `nft` actions redux thunk
4. Removed fungibleTokensService from the wallet object; it gained nothing from being present there as it is now a stateless singleton that can be imported and used wherever we want
> Ensure that current account state is used when calling fungibleTokensService.transfer()

- src/translations/zh-hans.global.json
- src/translations/zh-hant.global.json
We found one translation issue of the `notSupportedPhone` message, when user tries to import account with SMS. 
Here we'd like to fix the issue.
> Fix `zh` translation of `notSupportedPhone`

- src/components/common/GlobalAlert.js
Resolves: #1974
An easy fix to just remove the `en-us` i18n route. 
Zendesk pages will automatically redirect user to the English or Chinese pages based on their browser languages.
> Add i18n support of Zendesk FAQ URLs

- src/components/navigation/DesktopContainer.js
- src/components/navigation/MobileContainer.js
Fixes #1929 
Basically indent the text so that its hidden behind the css `background-image`
This fixes the issue on Desktop and also for Mobile only when `showNavLinks` is `false`.
This has no effect on Mobile when `showNavLinks` is `true` since a more specific `text-indent` will override
> Fix Firefox glitch where selected language is partially visible behind Language Switch

- src/actions/account.js
- src/components/accounts/RecoverAccountSeedPhrase.js
- src/components/accounts/RecoverWithLink.js
- src/components/accounts/ledger/SignInLedger.js
This fixes issue with NFTs, FTs, or/and staking data lingering after the user recovers a new account.
> Recover account: clear previous account state after recovery

- src/components/accounts/CreateAccount.js
- src/components/accounts/LinkdropLanding.js
This removes the automatic redirect to `/linkdrop` for linkdrops that use the `/create` route. More context can be found [here](https://github.com/near/near-wallet/issues/1982#issuecomment-893769813).
Example behavior:
Linkdrop for when you want users to **always create a new account**:
`https://wallet.near.org/create/someFundingContract/someFundingKey`
Linkdrop for when you want users to be able to **choose between creating a new account, or claim to existing**:
`https://wallet.near.org/linkdrop/someFundingContract/someFundingKey`
> Linkdrops: remove support for automatic redirect from /create to /linkdrop

- src/components/common/balance/BalanceDisplayUSD.js
- src/components/common/balance/helpers.js
Fixes issue with converting NEAR amounts greater than 1,000 NEAR to USD
> USD value: fix conversion for >1k NEAR amount and add commas

- src/components/navigation/UserAccounts.js
@Patrick1904 @marcinbodnar I made some small changes to the CSS of the desktop dropdown as per Patrick's request to prevent some bugs that were being caused by the previous flex-box implementation. A couple things to note:
1. `Button` elements should be used for buttons. There's really no reason we should be using `span` or `div` for buttons. This contributes to unexpected behavior in conjunction with `flex` properties, and is also semantically incorrect. The `UserAccounts` component here uses a `span` for the "Sync" button. Unfortunately, simply changing this to a `button` element isn't feasible without further refactoring considering all the things that have been done to make the `span` respond to user input like a `button`. We will need to do this though, so if you find yourself …
> Fix account switcher flex-box bugs

- packages/frontend/src/components/wallet/ActivityBox.js
We've received feedback from users that timestamps for minutes/months displayed under 'recent activity' on the dashboard are confusing.
Timestamps will now show: `s, min, hr, d, w, mo, y` (suggested by @corwinharrell).
> Recent activity: Adjust timestamp abbreviations

- packages/frontend/src/components/accounts/LinkdropLanding.js
- packages/frontend/src/components/accounts/SetupSeedPhrase.js
- packages/frontend/src/components/accounts/ledger/SetupLedger.js
- packages/frontend/src/components/accounts/recovery_setup/SetupRecoveryMethod.js
- packages/frontend/src/components/wallet/LinkDropSuccessModal.js
- packages/frontend/src/components/wallet/Wallet.js
- packages/frontend/src/reducers/index.js
- packages/frontend/src/slices/linkdrop.js
- packages/frontend/src/utils/wallet.js
Changes:
1. Store linkdrop amount in `Redux` vs `localStorage` since we do not want to persist the amount if the user navigates away from the Wallet (with a `redirectUrl` for example) post claiming the linkdrop.
Additional context here: https://github.com/near/near-wallet/issues/2013
A good place to create linkdrops for testnet: https://near-drop-testnet.onrender.com/
> Store linkdrop amount in Redux vs localStorage

- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/accounts/RecoverWithLink.js
Changes:
1. Always require `accountId` and `seedPhrase` from URL params to land on the `/recover-with-link` page.
> Always require account ID and phrase in the URL to land on /recover-with-link

- packages/frontend/src/reducers/ledger/index.js
- packages/frontend/src/translations/en.global.json
Always show "You will need to confirm the transaction details on your Ledger." in the `LedgerConfirmActionModal` when asking user to confirm the TX. The component has been relying on proper translation strings for every action to be signed with the Ledger, and some actions have not had strings available (or translated), which has degraded the UX with a `no translation found...` or instructions in the wrong language.
In addition, the 'confirm instruction string' has only been a conclusion of the TX that needs to be signed, not listing the specific TX info that the user should expect to see and confirm on the Ledger.
Improvement opportunity: [**Show explicit list of TXs and all information**](https://github.com/near/near-wallet/issues/1898) that the user should expect to confirm on the …
> Ledger confirm TX message: Instruct user to confirm TX details on Ledger

- packages/frontend/src/components/wallet/ActivityBox.js
- packages/frontend/src/components/wallet/TokenAmount.js
- packages/frontend/src/components/wallet/TokenBox.js
- packages/frontend/src/components/wallet/Wallet.js
Changes:
1. Show token name on the left side of the list, and add token symbol next to the amount, on the right side of the list.
2. Add comma formatting for larger token amounts - e.g.  1000000.000 nUSDC --> 100,000.000 nUSDC
3. Adds ellipsis treatment to token name when needed
> Token list display improvements

- packages/frontend/src/actions/staking.js
- packages/frontend/src/components/login/LoginDetails.js
Fixes #2011 
- Removes dependency on github user content JSON file which has not been updated in around 6 months.  This will allow Chinese users to load the staking page without being on a VPN that can access github.com! 🎉 
- Finds staking pools using indexer query by way of `near-contract-helper` (near/near-contract-helper/pull/478)
> Look up staking pools via indexer

- packages/frontend/src/reducers/selectors/balance.js
Profile 'Lockup balance': deduct 'staking' balance to align with 'Wallet balance'
This is a followup fix for https://github.com/near/near-wallet/pull/2076
> Profile 'Lockup balance': deduct 'staking' balance

- packages/e2e-tests/global-setup.js
- packages/e2e-tests/loginWithDapp/models/Login.js
- packages/e2e-tests/loginWithDapp/models/TestDapp.js
- packages/e2e-tests/loginWithDapp/signedInUser.spec.js
- packages/e2e-tests/loginWithDapp/signedInUserFAK.spec.js
- packages/e2e-tests/package.json
- packages/e2e-tests/playwright.config.js
- packages/e2e-tests/register/models/CreateAccount.js
- packages/e2e-tests/register/seedPhrase.spec.js
- packages/e2e-tests/testDapp/index.html
- packages/e2e-tests/testDapp/index.js
- packages/e2e-tests/testDapp/server.js
- packages/e2e-tests/utils/account.js
- packages/e2e-tests/utils/config.js
- packages/e2e-tests/yarn.lock
- packages/frontend/src/components/login/LoginConfirm.js
- packages/frontend/src/components/login/LoginForm.js
- packages/frontend/src/components/login/SelectAccountDropdown.js
- End to end tests and assertions for login with dapp flows. Creates a test account and then asserts an access key exists in local storage for that account after access is granted through the flow and that no pending key exists.
- Added a POM for login page `/login`.
> ADD tests for login with dapp flows

- packages/frontend/src/utils/wallet.js
Reverts near/near-wallet#2149
This PR broke balance loading on the main dashboard -- it spins indefinitely and never loads NEAR token balance when this code is changed.
My suspicion is that the existing logic relied on an empty string being falsy to fall back to `this.accountId`, but function signature's defaults check _existence_, not falsyness, to identify if they should be applied.
cc: @marcinbodnar
> Revert "Fix Parse error"

- packages/frontend/package.json
- packages/frontend/src/components/accounts/create/verify_account/VerifyAccountWrapper.js
- packages/frontend/src/components/accounts/recovery_setup/SetupRecoveryMethod.js
- packages/frontend/src/index.js
- packages/frontend/yarn.lock
Replaces `react-google-recaptcha-v3` with `react-google-recaptcha-v3-near`, which fixes Enterprise ReCAPTCHA not using `recaptcha.net`.
Hopefully we can undo this and delete the `react-google-recaptcha-v3-near` package entirely, when/if @t49tran accepts/merges this issue/PR:
https://github.com/t49tran/react-google-recaptcha-v3/issues/103
> Ensure Enterprise ReCAPTCHA loads from `recaptcha.net`

- packages/frontend/src/utils/wallet.js
Change 'reserved for transactions' amount from 0.01N to 0.05N to ensure there's enough funds while staking/sending 'max amount'.
> Change 'reserved for transactions' amount from 0.01N -> 0.05N

- packages/frontend/src/components/accounts/recovery_setup/SetupRecoveryMethod.js
- packages/frontend/src/translations/en.global.json
**Problem**
We've had reports that sometimes creating an identity funded account w/ coin-op 1.5 returns an error, but the account is still successfully created. Currently we automatically send the user to the 'self funded' options page if an error occurs, which causes confusion since the account is already created.
**Solution**
This fix catches the error returned when calling `createIdentityFundedAccount`. Checks if the account exists on chain. If the account exists, it checks that the users public key also exists on the account, to verify ownership. It then attempts to finish the 'post account creation' setup by adding a local key, etc. If that fails, the user is redirected to the `/recover-account` route, for manual account recovery.
If the account exists, but the user is not the owner, …
> Create w/ link + coin-op 1.5: handle error

- packages/frontend/package.json
- packages/frontend/src/redux/actions/staking.js
- packages/frontend/src/services/FungibleTokens.js
- packages/frontend/src/utils/account-with-lockup.js
- packages/frontend/src/utils/staking.js
- packages/frontend/src/utils/wallet.js
- packages/frontend/yarn.lock
Upgrade `near-api-js` to latest. 
Continues work done in https://github.com/near/near-wallet/pull/1728 and <s>adds `.call` to maintain `this` context [here](https://github.com/near/near-wallet/pull/2248/commits/a47b710f9c891f2a67dd981f58025de7e00d0f19#diff-46f345c520c144e0d8300842ff78d012a61770029e9d262aaf62632d95960486R36)</s> removes v1 usages of account `signAndSendTransaction` and `functionCall` in favor of v2 APIs.
> Upgrade near api js 0.43.1

- packages/frontend/src/services/NonFungibleTokens.js
This PR updates visualization of NFT for displaying the data which is taken from NFT metadata directly.
Testing plan
===
Tested on `nenene.testnet`
Data loaded from metadata: `data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MCIgaGVpZ2h0PSI1MCI+PGNpcmNsZSBjeD0iMjUiIGN5PSIyNSIgcj0iMjAiIHN0cm9rZT0ib3JhbmdlIiBzdHJva2Utd2lkdGg9IjQiIGZpbGw9InllbGxvdyIgLz48L3N2Zz4=`
> support loading NFT image from data: URI

- packages/frontend/src/components/login/v2/ConfirmLogin.js
- packages/frontend/src/components/login/v2/ConfirmLoginWrapper.js
- packages/frontend/src/components/login/v2/ConnectWithApplication.js
- packages/frontend/src/components/login/v2/GrantFullAccessModal.js
- packages/frontend/src/components/login/v2/NetworkFeeAllowance.js
- packages/frontend/src/components/login/v2/SelectAccountLogin.js
- packages/frontend/src/components/login/v2/SelectAccountLoginWrapper.js
- packages/frontend/src/components/svg/ArrowUpRight.js
- packages/frontend/src/redux/actions/account.js
- packages/frontend/src/routes/LoginWrapper.js
> App login: display contract ID

- .travis.yml
- packages/frontend/package.json
- packages/frontend/yarn.lock
- Updated to latest FOSSA CLI
- Removed now unnecessary `init` command
- Removed now unnecessary `--server-scan` argument to the `analyze` command
- Updated `redux-toolkit` version to fix immer.js transitive dependency (prototype pollution issue)
> Fix FOSSA PR checks

- packages/frontend/src/config.js
- packages/frontend/src/redux/actions/staking.js
- packages/frontend/src/redux/reducers/selectors/balance.js
- packages/frontend/src/utils/account-with-lockup.js
* Use [constant](https://github.com/near/core-contracts/blob/master/lockup/src/lib.rs#L33) (3.5 / 35 Ⓝ) conditional on PR # changing lockup_contract.wasm on [core-contracts repo](https://github.com/near/core-contracts) instead of always defaulting to old storage constant (35 Ⓝ)
* If transfers are disabled use current time as enabled timestamp
* If `lockupTimestamp` was used amount released will be unaffected and will be based only on that timestamp
* If `lockupDuration` was used amount will be locked since that duration is meant to be added to timestamp when transfers are enabled
* Include calculation of unvested funds in locked amount. Fixes #2014 
* Modify calculation of `liquidOwnersBalance` to use contract call on`get_liquid_owners_balance`
* Add new code hash broken timestamp from …
> ADD modifications to lockup balance display

- packages/frontend/src/hooks/fungibleTokensIncludingNEAR.js
- packages/frontend/src/redux/slices/tokens/index.js
The fungible token list is randomly sorted on each page reload, which makes it hard to locate a specific token. This fix sorts the fungible token list alphabetically by `token.name` so that it's easier to locate tokens.
> Fungible token list: sort alphabetically

- packages/frontend/src/redux/actions/account.js
Currently using `accountId` from redux and can result in `undefined` on a slow connection. `wallet.accountId` is available right when the UI renders.
> allowLogin: use wallet.accountId for faster access on slow connection

- packages/frontend/.dockerignore
- packages/frontend/Dockerfile
…mage size
Drops image size from 1.1GB -> 323MB (and it's still so big just because the Phusion base image is 183MB)
> Switch to multistage build for Wallet Dockerfile, shedding 700MB of image size

- package.json
This PR updates the `scripts` in `package.json` to replace instances of `yarn` (implicit `install`) with: `yarn install --frozen-lockfile`. Addresses #2311
> bug: use --frozen-lockfile to install packages according to yarn.lock versions

- packages/frontend/README.md
This PR adds a blurb explaining the need for a valid `NEAR_WALLET_ENV` environment variable. Now that we have feature flags in the repo this variable is required.
> docs: add documentation on NEAR_WALLET_ENV in the Getting Started section

- packages/frontend/src/components/profile/Profile.js
- packages/frontend/src/components/profile/balances/BalanceContainer.js
- packages/frontend/src/components/staking/StakingContainer.js
- packages/frontend/src/redux/actions/account.js
- packages/frontend/src/redux/actions/staking.js
- packages/frontend/src/redux/reducers/account/index.js
- packages/frontend/src/redux/reducers/allAccounts/index.js
- packages/frontend/src/redux/reducers/staking/index.js
- packages/frontend/src/redux/slices/account/index.js
- packages/frontend/src/redux/slices/allAccounts/index.js
- packages/frontend/src/utils/account-with-lockup.js
Error described in #2245 fixed by changing how `lockupIdExists` in `getProfileStakingDetails` action is set. Additionally handled `staking.getLockup` in `account` reducer to set `hasLockup` value that will help to reason what should be done while setting `lockupIdExists`.`hasLockup` also used in `StakingContainer` component.
Additionally, I found another bug. The problem was that if the user wanted to enter the Staking page after the lockup account was deleted, Wallet crashed. That was because we are storing previously selected `accountId` for Staking page in the local storage - and if the user has previously selected lockup account, we were trying to load staking details for this lockup account - that was failing. 
Fixed it by adding functionality that will detect if the lockup account …
> Fix deleting lockup account and Staking page

- packages/frontend/src/redux/reducers/selectors/balance.js
Hotfix broken import of `MIN_BALANCE_FOR_GAS`. This is causing `reservedForTransactions` to be zero.
> FIX broken import of MIN_BALANCE_FOR_GAS

- packages/frontend/src/utils/account-with-lockup.js
Compute liquid amount locally instead of calling `get_liquid_owners_balance`. This is because `get_liquid_owners_balance` will return 0 when transfers are disabled on the lockup contract. Locally, we can call the transfer voting contract and compute the up to date liquid amount without spending gas to update the lockup contract. Gas will then be spent to update the lockup contract state when the user withdraws from the lockup via the wallet.
Closes #2349
> fix: compute liquid amount locally instead of fetching

- .husky/pre-commit
- package.json
- packages/frontend/.githooks/format-json
- packages/frontend/package.json
- packages/frontend/src/translations/en.global.json
- yarn.lock
Removed JSON alpha sort from pre-push since it'll be done on commit instead
JSON alpha sort now only runs on files in the currently staged changeset
Re-sorted our english terms file using json-sort
Added `concurrently` as an official dev dependency for `frontend`; previously we relied on it existing purely because some of our second level deps relied upon on.
**Without this code**, any time I pushed code, any un-formatted files in the repo would end up in my workspace as modified files
**With this code**, we only run json format on files I've specifically changed, and we run the reformatting _before the commit happens_, so our commits end up properly formatted in the commit content itself.
> chore: Add pre-commit hook to run lint fix and JSON alpha sort

- packages/frontend/src/components/accounts/CreateAccount.js
- packages/frontend/src/components/accounts/create/existing_account/SelectAccount.js
- packages/frontend/src/components/common/FormButtonGroup.js
- packages/frontend/src/redux/actions/account.js
- packages/frontend/src/redux/slices/account/index.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/translations/pt.global.json
- packages/frontend/src/translations/ru.global.json
- packages/frontend/src/translations/vi.global.json
- packages/frontend/src/translations/zh-hans.global.json
- packages/frontend/src/translations/zh-hant.global.json
- packages/frontend/src/utils/account.js
Adds conditional logic to routes on the create account flow if the currently active account is an implicit account:
* Display “Add a Custom Address” copy on `/create`
* Skip `/verify-account-id screen`
* Hide cancel button on `/fund-with-existing-account`
> Fund account with implicit flow

- packages/frontend/src/components/staking/components/BalanceBox.js
- packages/frontend/src/components/staking/components/Validator.js
- packages/frontend/src/components/staking/components/ValidatorBox.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/translations/pt.global.json
- packages/frontend/src/translations/ru.global.json
- packages/frontend/src/translations/vi.global.json
- packages/frontend/src/translations/zh-hans.global.json
- packages/frontend/src/translations/zh-hant.global.json
1. Alphabetizes the JSON files now that we have automatic tooling added to handle this whenever they are edited
2. Updates copy for token farm validators
> chore: Update staking farm related copy

- packages/frontend/src/components/Routing.js
hotfix to disable implicit account creation flow on testnet and always use named account creation flow.
> fix: disable implicit acc creation flow on testnet

- .git-hooks/helpers/detect-foxtrot-merge
- .husky/post-merge
- .husky/pre-push
- .husky/pre-receive
Adds hooks to warn you when you have just created a foxtrot commit, and to block pushing branches to the remote that contain those commits.  
Apart from the issue of bundling up changes that were not part of the feature branch's changeset into that branch, making it difficult or impossible to revert a merged branch without possibly breaking other code, this is going to be especially critical as we start generating changelog output using conventional commit contents, as not being able to follow the 'first parent' path can create serious problems with tooling that tries to generate changelog diffs automatically.
Further reading at:
https://git-blame.blogspot.com/2012/03/fun-with-first-parent.html
http://bit-booster.blogspot.cz/2016/02/no-foxtrots-allowed.html …
> Disallow foxtrot commits

- packages/frontend/src/config/environmentDefaults/development.js
- packages/frontend/src/config/environmentDefaults/mainnet.js
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.js
- packages/frontend/src/config/environmentDefaults/testnet.js
[https://awesomenear.com/trending/](https://awesomenear.com/trending/)
Removing the 'trending' category as it's not active anymore.
> fix: Modify 'explore apps' link URL

- packages/frontend/src/components/accounts/create/landing/CreateAccountLanding.js
**`trackingId='get started setup-recovery-implicit'`**
> chore: Add tracking to create implicit account 'get started' btn

- packages/frontend/src/utils/account-with-lockup.js
Fix liquid amount calculation to use `MIN_BALANCE_FOR_STORAGE` instead of `MIN_BALANCE_FOR_GAS`
closes #2436
> fix: misplaced usage of MIN_BALANCE_FOR_GAS

- packages/frontend/src/components/send/SendContainerV2.js
- packages/frontend/src/components/staking/components/Staking.js
- packages/frontend/src/components/staking/components/Validator.js
- packages/frontend/src/components/wallet/Tokens.js
- packages/frontend/src/hooks/fungibleTokensIncludingNEAR.js
- packages/frontend/src/redux/slices/tokens/index.js
- packages/frontend/src/services/FungibleTokens.js
Fix loading state on receiver screen when use max is used:
- Make dependency for clearing user input more specific (`contractName` || `symbol`)
- Pass `token.balance` to `EnterReceiver` component when `isMaxAmount` is `true`
- Replace `useNEARAsTokenWithMetadata` with memoized selector `selectNEARAsTokenWithMetadata` to avoid new identity unless the state changed
> fix: loading on receiver screen when use max is used

- packages/frontend/src/components/accounts/recovery_setup/SetupRecoveryMethod.js
- packages/frontend/src/redux/actions/account.js
- packages/frontend/src/redux/slices/sign/index.js
Use `.replace` to update query params
Closes #2452
> fix: use `.replace` to update query params

- packages/frontend/src/components/GlobalStyle.js
- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/accounts/create/passphrase/GeneratePassphrase.js
- packages/frontend/src/components/accounts/create/passphrase/SharedPassphrase.js
- packages/frontend/src/components/accounts/create/passphrase/SharedPassphraseList.js
- packages/frontend/src/components/accounts/create/passphrase/VerifyPassphrase.js
- packages/frontend/src/components/accounts/recovery_setup/RecoveryOption.js
- packages/frontend/src/routes/GeneratePassphraseWrapper.js
- packages/frontend/src/routes/SharedPassphraseWrapper.js
- packages/frontend/src/routes/VerifyPassphraseWrapper.js
- packages/frontend/src/translations/en.global.json
This PR adds the necessary UI for enabling 'shared passphrase' while creating a new account. This feature will be finalized and launched once we add necessary UX to manage shared passphrases outside of the account creation flow, as outlined here: https://github.com/near/near-wallet/issues/2348#issuecomment-1034110613.
Figma design: https://www.figma.com/file/yR4qz7oAjAiVAJ0hJSnQQj/Onboarding-Exploration?node-id=1%3A606
> Add UI for shared passphrase when creating a new account

- packages/frontend/src/utils/helper-api.js
Bugfix: Restore behaviour which permits optional redirect urls in some routes (such as login)
> fix: restore support for optional redirect URLs

- packages/frontend/src/components/profile/two_factor/TwoFactorAuth.js
- packages/frontend/src/config/configFromEnvironment.js
- packages/frontend/src/config/environmentDefaults/development.js
- packages/frontend/src/config/environmentDefaults/mainnet.js
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.js
- packages/frontend/src/config/environmentDefaults/testnet.js
Add empty contract `E8jZ1giWcVrps8PcV75ATauu6gFRkcwjNtKp7NKmipZG` to enable 2fa button whitelist. Similar to [#736](https://github.com/near/near-api-js/pull/736) in near-api-js but in wallet scope. Temporary patch to disable button only.
> fix: add 'empty' contract to enable 2fa button whitelist

- packages/frontend/src/components/accounts/SetupSeedPhrase.js
- packages/frontend/src/components/wallet/ActivityDetailModal.js
- packages/frontend/src/redux/slices/availableAccounts/index.js
- packages/frontend/src/redux/slices/handleAsyncThunkStatus.js
- packages/frontend/src/redux/slices/ledger/index.js
- packages/frontend/src/redux/slices/nft/index.js
- packages/frontend/src/redux/slices/recoveryMethods/index.js
- packages/frontend/src/redux/slices/sign/index.js
- packages/frontend/src/redux/slices/tokenFiatValues/index.js
- packages/frontend/src/redux/slices/tokens/index.js
- packages/frontend/src/redux/slices/transactions/index.js
Creating `handleAsyncThunkStatus` helper function that simplifies and allows to automatically handle status objects for reducers. 
It's prepared using `addMatcher` because we need to handle situations when we would like to use `.pending`/`.fulfilled`/`.rejected` for additional functionality. And it's not allowed to use more than one `addCase` for the same action status.
> handleAsyncThunkStatus helper function to handle repeated patterns for the status state object

- packages/frontend/tools/disable-2fa-with-seedphrase/README.md
- packages/frontend/tools/disable-2fa-with-seedphrase/disable-2fa-with-seedphrase.sh
Add script allows the user to disable NEAR Wallet 2fa using the provided seedphrase
> feat: add script to disable 2fa using seedphrase

- packages/frontend/src/components/sign/v2/SignTransactionSummary.js
- packages/frontend/src/components/sign/v2/SignTransactionSummaryWrapper.js
- packages/frontend/src/routes/SignWrapper.js
This PR adds a flag prop to the transaction signing components to prevent approving transactions when the active account has not yet switched over to the signing account. This will always be temporary since the account is guaranteed to be valid to render the button and the wrapper dispatches the action to switch accounts if the active account does not match the signing account.
Closes #2482
> fix: prevent transaction approval until account matches signer

- packages/frontend/src/components/common/radio_button/RadioButton.js
- packages/frontend/src/components/wallet/ActivitiesWrapper.js
Fixes misaligned button on `/staking`
> fix: Fix staking account selector button alignment

- packages/frontend/src/utils/constants.js
This PR adds support for validators using wallet factory `factory.colorpalette.testnet` as well as aurora's `factory01.littlefarm.testnet`
> chore: add new project validator factory to regex

- packages/frontend/src/components/sign/SignTransferInvalid.js
- packages/frontend/src/routes/SignWrapper.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/translations/pt.global.json
- packages/frontend/src/translations/ru.global.json
- packages/frontend/src/translations/vi.global.json
- packages/frontend/src/translations/zh-hans.global.json
- packages/frontend/src/translations/zh-hant.global.json
This PR applies the fix from `stable` in which callback URLs used in signing transactions are considered invalid when they contain JavaScript code.
> fix: Invalid transfer url

- packages/frontend/src/components/accounts/two_factor/EnableTwoFactor.js
- packages/frontend/src/components/accounts/two_factor/TwoFactorOption.js
- packages/frontend/src/components/profile/hardware_devices/ConfirmDisable.js
- packages/frontend/src/components/profile/two_factor/TwoFactorAuth.js
- packages/frontend/src/translations/en.global.json
This PR removes the option for enabling 2FA with SMS and it's associated code. As we will most likely expand out these options again in future the concept of "options" still remains in code.
Removing SMS leaves us with a single option making the radio options a bit redundant but we've decided to push this out as is to stop new SMS 2FA accounts ASAP. An updated UI will be addressed in a follow up PR.
> WAL-115 Remove option for enabling 2FA with SMS

- packages/frontend/.eslintrc.js
- packages/frontend/src/redux/reducers/account/index.js
- packages/frontend/src/routes/LoginWrapper.js
This PR adds a new eslint dependency and rules to verify the existence of named imports, ensuring that we no longer reference named imports not exported from the target module.
> style(lint): nonexistent named imports error

- features/features.d.ts
- features/flags.json
- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/accounts/import/ImportAccountWithLink.js
- packages/frontend/src/routes/ImportAccountWithLinkWrapper.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/translations/pt.global.json
- packages/frontend/src/translations/ru.global.json
- packages/frontend/src/translations/tr.global.json
- packages/frontend/src/translations/vi.global.json
- packages/frontend/src/translations/zh-hans.global.json
- packages/frontend/src/translations/zh-hant.global.json
- packages/frontend/src/utils/helper-api.js
- packages/frontend/src/utils/wallet.js
https://nearinc.atlassian.net/browse/WAL-168
-------
~~Testnet account with a named and implicit account: [testing-pr-2521.testnet](https://near-wallet-pr-2521.onrender.com/recover-with-link/testing-pr-2521.testnet/mobile%20element%20anxiety%20giraffe%20beef%20brand%20pistol%20steak%20cook%20dad%20spatial%20found)~~
~~https://near-wallet-pr-2521.onrender.com/recover-with-link/testing-pr-2521.testnet/mobile%20element%20anxiety%20giraffe%20beef%20brand%20pistol%20steak%20cook%20dad%20spatial%20found~~
~~Testnet account with only a named account: [testing-pr-2521-1.testnet](https://near-wallet-pr-2521.onrender.com/recover-with-link/testing-pr-2521-1.testnet/loyal%20inhale%20milk%20neither%20eyebrow%20plate%20dinner%20super%20project%20hurt%20adjust%20game)~~ …
> feat: Add new 'import w/ link' UI

- packages/frontend/src/components/accounts/two_factor/TwoFactorVerifyInput.js
- packages/frontend/src/components/accounts/two_factor/TwoFactorVerifyModal.js
- packages/frontend/src/components/common/AlertBanner.js
- packages/frontend/src/components/common/balance/helpers.js
- packages/frontend/src/redux/actions/account.js
- packages/frontend/src/redux/reducers/account/index.js
- packages/frontend/src/redux/slices/account/index.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/utils/getTranslationsFromMultisigRequest.js
- packages/frontend/src/utils/twoFactor.js
With the migration to Twilio Verify 2FA SMS messages will no longer show the transaction details. This PR adds UI to the 2FA verification modal to render the same details which would be present in the SMS.
This is essentially a 1:1 replacement of the existing messaging _except_ for setting up SMS 2FA. I've left that out as we have disabled that flow.
> WAL-177 Render pending 2FA actions in confirmation modal

- packages/frontend/src/components/accounts/create/implicit_account/SetupRecoveryImplicitAccount.js
- packages/frontend/src/components/accounts/recovery_setup/SetupRecoveryMethod.js
- packages/frontend/src/routes/SetupRecoveryImplicitAccountWrapper.js
- packages/frontend/src/utils/wallet.js
This PR updates calls to the recovery method endpoints responsible for validating security codes to include the public key associated with the recovery method being validated. The public key will be used to uniquely identify the recovery method document in DynamoDB and so should be provided when calling any endpoint responsible for querying or mutating recovery methods.
> WAL-160 fix(recovery): provide publicKey to security code validation endpoints

- packages/frontend/src/services/NonFungibleTokens.js
This PR adds a `buildMediaUrl` method to the NFT class to simplify the logic around extracting URI data from NFT metadata. In particular it restores the logic responsible for rendering `data:image` URIs.
Closes #2534
> fix(nft): restore data URI scheme rendering for NFTs

- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/accounts/SetupSeedPhrase.js
- packages/frontend/src/components/accounts/SetupSeedPhraseForm.js
- packages/frontend/src/components/accounts/ledger/SetupLedger.js
- packages/frontend/src/components/common/styled/Container.css.js
- packages/frontend/src/redux/slices/flowLimitation/index.js
Fixes:
1. Disallow switching account on onboarding/recovery pages.
2. Makes sure to pull wallet recovery methods and disable the 'continue' button for already enabled recovery methods (regression).
To test:
1. While logged in to an account, navigate to any of the onboarding or/and recovery setup pages:
```
/create
/set-recovery
/setup-seed-phrase
/recover-account
/recover-seed-phrase
/sign-in-ledger
/fund-create-account
/verify-account
/initial-deposit
/setup-ledger
```
3. Expect the main navigation dropdown to disable option to switch account
4. Navigate to a different page and expect option to switch account to be enabled again
> fix: Disallow switching account on onboarding/recovery pages

- packages/frontend/src/redux/reducers/status/index.js
It one-line fix, but a few hours of tinkering and checking.
I analyzed several possible solutions. We cannot use `alert.data.data` (like is mentioned in the issue description) because it will interfere with other usages of global alerts that are proper. We cannot change `walletError` implementation because it's also used in two other cases, and it seems reasonable as it is. The only proper solution is to destructure `payload.data` into `data` prop in `actionStatus`. It's solving the problem properly.
Generally, we are planning to slowly get rid of global alerts in favor of custom error UI implemented in all functionalities. So basically every UI will have its own way to show error information.
> fix: passing data from WalletError to actionStatus state

- packages/frontend/src/redux/crossStateSelectors/selectNEARAsTokenWithMetadata.js
Fixing regression or missed reference introduced when adding ref-finance support for tokens other than NEAR native tokens.
> fix: Ensure NEAR token balance shows correct USD fiat value

- packages/frontend/src/components/accounts/two_factor/TwoFactorVerifyModal.js
- packages/frontend/src/components/login/v2/ConfirmLoginWrapper.js
- packages/frontend/src/redux/actions/account.js
Twilio Verify has several different rate limits which do not exist with the current SMS delivery service. This introduces new user error states which now need to be handled. These 2FA rate limits users are likely to encounter are:
* User has sent/resent the code too many times
* User has incorrectly verified the code too many times
* A pending verification was left for an extended period and expired
This PR will surface these error messages to the user via `<GlobalAlert />` and also close the 2FA modal preventing any further rate limited verifications/resends. From here, new transactions will be blocked until the rate limit has subsided (usually ~10mins).
> WAL-215 Twilio Verify error handling

- packages/frontend/src/redux/reducers/sign/index.js
When a user has 2FA enabled and gets rate limited by Twilio the sign request fails with no successful transactions, making `successHashes` `undefined`. This PR defaults `successHashes` to an empty array to prevent some of the down stream logic which assume it exists from failing:
> fix(sign): Prevent runtime error on failed sign tx

- packages/frontend/src/components/nft/NFTDetail.js
- packages/frontend/src/components/nft/NFTMedia.js
- packages/frontend/src/components/wallet/NFTBox.js
Users are unable to see their video NFTs on the NFT-detail screen when they click their NFTs. Video NFTs are not supported. 
- Users are able to video and regular image NFTs in the NFT details tab. 
| Before   |      After      |
|----------|:-------------:|
| ![Before](https://user-images.githubusercontent.com/25015977/160926699-acbc309d-043d-4b83-97b2-da5d4d3ff2e7.gif) | ![After](https://user-images.githubusercontent.com/25015977/160926716-119cf1a5-bc9d-4942-a285-ae183da9086d.gif) |
| Collectible Screen   |      NFT Detail Screen      |
|----------|:-------------:|
| <img width="648" alt="image" src="https://user-images.githubusercontent.com/25015977/160928198-04692767-f6ed-41be-9649-6648ed2b8b7b.png"> | <img width="625" alt="image" …
> feat: added video to show up on the NFT detail screen

- packages/frontend/src/components/accounts/RecoverAccount.js
- packages/frontend/src/components/common/VerifyWalletDomainBanner.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/utils/getWalletURL.js
Changes:
1. Show a 'verify wallet domain banner' on the main[ `/recover-account`](https://near-wallet-pr-2542.onrender.com/recover-account) route.
> Wallet domain banner

- packages/frontend/src/components/common/FormButton.js
- packages/frontend/src/components/profile/Profile.js
- packages/frontend/src/components/profile/remove_account/RemoveAccountModal.js
- packages/frontend/src/components/profile/remove_account/RemoveAccountWrapper.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/utils/localStorage.js
- packages/frontend/src/utils/wallet.js
https://nearinc.atlassian.net/browse/WAL-58
**Description**
This feature allows users to remove a single account from the wallet. The wallet automatically makes the next available account active once the user removes an account. The user is redirected to the guest landing page if no other accounts are available.
**Notes**
All changes to keys are limited to the browsers `localStorage`. There are currently no changes made to keys on-chain.
> feat: Enable 'Remove Wallet Account'

- packages/frontend/src/components/login/v2/ConfirmLogin.js
- packages/frontend/src/components/login/v2/PermissionItem.js
- packages/frontend/src/translations/en.global.json
This PR adresses concerns in and closes #2567 :
* Adds a new permission display regarding the ability to call methods on the contract
> feat: added additional permission to LAK login display

- packages/frontend/src/components/common/styled/Container.css.js
Fixes lack of spacing between buttons in the ledger sign in page
> fix: Fix button margin on ledger pages

- packages/frontend/src/components/wallet/TokenBox.js
Show `NEAR` and token symbols correctly depending on feature flags
> fix: show NEAR symbol when flag off

- packages/frontend/src/components/wallet/TokenBox.js
- packages/frontend/src/hooks/fungibleTokensIncludingNEAR.js
- Fix the fallback logic on the fiat value selector to only fallback when fiat data actually exists
- Fix the conditional text alignment on the token list component
> fix: fiat selector and text align

- packages/frontend/src/components/accounts/two_factor/TwoFactorVerifyModal.js
- packages/frontend/src/utils/getTranslationsFromMultisigRequest.js
Fixes: #2597
When the `FunctionCall` args is not JSON, display the raw base64 string, so it won't break the user workflow when the contract is `aurora`.
Please give this high priority if possible, so it won't stop the release of some important features of Ref Finance.
> fix: fallback to string if args cannot be parsed as JSON

- features/features.d.ts
- features/flags.json
- packages/frontend/src/components/navigation/NavLinks.js
- packages/frontend/src/config/environmentDefaults/development.js
- packages/frontend/src/config/environmentDefaults/mainnet.js
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.js
- packages/frontend/src/config/environmentDefaults/testnet.js
- packages/frontend/src/redux/actions/staking.js
- packages/frontend/src/services/FungibleTokens.js
- packages/frontend/src/services/NonFungibleTokens.js
- packages/frontend/src/services/indexer.js
- packages/frontend/src/utils/account-with-lockup.js
- packages/frontend/src/utils/explorer-api.js
- packages/frontend/src/utils/helper-api.js
- packages/frontend/src/utils/staking.js
This PR adds an indexer service responsible for calling out to the contract helper REST endpoints responsible for querying the indexer. Aside from consolidating this logic in one module, this change introduces a new set of service URLs pointed to the new backend indexer service which has been separated from the contract helper for performance and stability concerns.
> feat(indexer): indexer service

- packages/frontend/package.json
- packages/frontend/src/components/accounts/CouldNotFindAccountModal.js
- packages/frontend/src/components/accounts/RecoverAccountSeedPhrase.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/utils/isValidSeedPhrase.js
- packages/frontend/src/utils/wallet.js
- yarn.lock
Referencing issues:
https://nearinc.atlassian.net/browse/WAL-193
https://nearinc.atlassian.net/browse/WAL-191
This PR enables import of a 'zero balance account' when importing an account with seed phrase on the `/recover-seed-phrase` route.
The wallet first tries to find all associated accounts using the provided seed phrase, and shows a modal with 'no accounts found' in case of no active accounts found. The user is then presented with a button to 'import anyway', which converts the seed phrase into an implicit account and imports it into the wallet.
The wallet runs a check against the provided seed phrase using [bip39-light](https://www.npmjs.com/package/bip39-light) to ensure that the provided seed phrase is valid. The wallet shows the error toast in case the provided seed phrase is:
1. …
> Seed phrase import: enable import of zero balance account

- packages/frontend/src/config/environmentDefaults/development.js
- packages/frontend/src/config/environmentDefaults/testnet.js
Update `LOCKUP_ACCOUNT_ID_SUFFIX` defaults to `lockup.devnet` for testnet and development `NEAR_WALLET_ENV`s.
This will allow lockup testing using [tesnet.lockup.tech](https://testnet.lockup.tech/).
> chore: update LOCKUP_ACCOUNT_ID_SUFFIX defaults

- packages/frontend/ci/config.js
- packages/frontend/src/config/configFromEnvironment.js
- packages/frontend/src/config/index.js
This PR sets `CLOUDFLARE_BASE_URL` as a default value for nearorg environments. Current netlify and render instances have already been moved to `NEARORG` environments (except mainnet pending merge to `stable`) and `CLOUDFLARE_BASE_URL` was set on the UI
> chore: set CLOUDFLARE_BASE_URL as default for nearorg envs

- packages/frontend/src/config/environmentDefaults/testnet_STAGING.js
- packages/frontend/src/config/index.js
This PR adds configuration for the as-yet unused `testnet_STAGING` environment. It is currently identical to the `testnet` configuration.
> feat(env): add configuration for testnet_STAGING

- packages/frontend/src/components/accounts/ledger/LedgerHdPaths.js
- packages/frontend/src/components/accounts/ledger/SignInLedgerViews/Authorize.js
- packages/frontend/src/components/accounts/ledger/SignInLedgerViews/EnterAccountId.js
- packages/frontend/src/components/accounts/ledger/SignInLedgerWrapper.js
- packages/frontend/src/redux/slices/ledger/index.js
Changes:
- fixing closing dropdown while changing HD path - now it will close only when confirmed by clicking a button
- fixing saving HD path in the local storage - before HD path was saved only if it wasn't the default path, which causes a few problems, now it's saved always in `signInWithLedgerAddAndSaveAccounts` thunk so it's always up to date
- fixing choosing HD path, it was problematic if a user opens dropdown and changed path a few times
- fixing closing dropdown without any action
> Fix sign in with ledger errors

- features/flags.json
- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/Swap/views/SwapPage.js
- packages/frontend/src/components/navigation/NavLinks.js
- packages/frontend/src/components/wallet/TokenBox.js
- packages/frontend/src/components/wallet/Wallet.js
- packages/frontend/src/translations/en.global.json
This PR:
- Enables USN feature on non `_NEARORG` environments
- Re-adds the USN route (removed in #2621)
- Updates the USN route to `/swap-usn` from `/swap-money`
- Updates the copy on the Swap button, Swap navlink and `swap-usn` title to "Swap USN" from "Swap" to avoid duplicate
> fix: enable and fix USN with copy update

- packages/frontend/src/components/wallet/Wallet.js
Wrap wallet buttons on the wallet dashboard on overflow
> feat: wrap wallet buttons on overflow

- packages/frontend/src/components/navigation/DesktopContainer.js
Reverts near/near-wallet#2677
Reverting this fix as it causes desktop menu to be hidden because of overflow
> Revert "fix: Fix desktop nav horizontal overflow"

- packages/frontend/src/components/accounts/CouldNotFindAccountModal.js
- packages/frontend/src/components/accounts/CouldNotFindAccountModalWrapper.js
- packages/frontend/src/components/accounts/ledger/SignInLedgerWrapper.js
- packages/frontend/src/translations/en.global.json
This enables a user to import a non-existent Ledger implicit account into the wallet (on testnet)
To test:
1. Go to `https://my-near-wallet-pr-2679.onrender.com/sign-in-ledger`
2. Change Ledger HD path to any path without an existing account
3. Try importing the account
4. Click 'Import anyway' when prompted
5. Confirm key on Ledger device
6. Observe that the Ledger account has been imported with given key
> feat: Enable import of zero balance Ledger account (testnet)

- packages/frontend/src/components/staking/StakingContainer.js
- packages/frontend/src/components/staking/components/BalanceBox.js
- packages/frontend/src/components/staking/components/Staking.js
- packages/frontend/src/components/staking/components/Validator.js
- packages/frontend/src/redux/actions/staking.js
- packages/frontend/src/redux/crossStateSelectors/selectCollectedAvailableForClaimData.js
- packages/frontend/src/redux/reducers/staking/index.js
- packages/frontend/src/redux/slices/staking/index.js
Bug fix to correctly display accumulated farm rewards for lockup accounts as well as main account when the radio toggle is visible. Also refetch unclaimed rewards when the selected account changes to a lockup account on the staking dashboard.
This can be tested by deploying a lockup using https://testnet.lockup.tech/ on the deploy preview
cc: @askulikov
> fix: key farmRewards by accountId

- features/flags.json
- packages/frontend/src/components/profile/Profile.js
- packages/frontend/src/components/profile/zero_balance/AddLedgerKeyModal.js
- packages/frontend/src/components/profile/zero_balance/ZeroBalanceAccountWrapper.js
- packages/frontend/src/redux/slices/account/createAccountThunks.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/utils/wallet.js
Changes:
1. Finalize wallet setup by adding a new key in `localStorage` when the zero balance account is active/funded. This final setup happens when the user navigates to the user `/profile` since the main reason for a `localStorage` key is for Ledger to pull and manage recovery methods. Non-ledger users do not in theory need a new access key for `localStorage` since the initial key is already present, however, it will be added for consistency sake since that's the current behavior during onboarding and when importing an account.
2. Turn `off` the feature flag `IMPORT_ZERO_BALANCE_ACCOUNT` in all environments until we've shipped the final pieces.
Main way to test the UI/UX here is to:
1. Change the flag `IMPORT_ZERO_BALANCE_ACCOUNT` to `on` in your environment
2. Import an implicit …
> feat: Finalize wallet setup for funded zero balance account

- packages/frontend/src/redux/actions/staking.js
Accounts with 2FA enabled are not able to claim validator rewards.
Currently, validator `Contracts` have no awareness of 2FA enabled accounts. This means contract calls are signed with the limited access 2FA key rather than going through the accounts multisig contract. This results in an error for function calls which also have a `deposit`, like `claim`, as these [must be signed with a full access key](https://github.com/near/nearcore/blob/master/core/primitives/src/errors.rs#L170).
This PR updates validator `Contract` to be instantiated with a 2FA aware `Account`.
> WAL-321 Claim validator rewards on 2FA enabled account

- packages/frontend/src/redux/actions/staking.js
`getValidators` creates an `Account` with the passed `accountId` to call view methods on the validator contracts. Now that this `Account` is 2FA aware (#2680), it will also call `account.state()` to check if the current account has 2FA enabled. This call will fail if the original `accountId` is `undefined`, which `exAccountId` sometimes is. This PR updates `getValidators()` call to use `accountId` which is known to exist.
> fix: Ensure `Account` is instantiated with valid `accountId`

- packages/frontend/src/components/accounts/recovery_setup/new_account/ConfirmPassphrase.js
- packages/frontend/src/components/accounts/recovery_setup/new_account/SetupPassphraseNewAccount.js
- packages/frontend/src/redux/slices/account/createAccountThunks.js
- packages/frontend/src/routes/SetupLedgerNewAccountWrapper.js
- packages/frontend/src/routes/SetupPassphraseNewAccountWrapper.js
- packages/frontend/src/routes/SetupRecoveryImplicitAccountWrapper.js
- packages/frontend/src/translations/en.global.json
This PR treats an implicit account as a 'zero balance account' during onboarding and therefore skips the funding step and sends the user directly to the wallet dashboard.
The feature (`IMPORT_ZERO_BALANCE_ACCOUNT`) is currently turned `OFF` in all environments, and a separate PR to turn the feature `ON` on `testnet` and `staging` will be opened once this PR is merged.
To test this PR, simply turn the flag `IMPORT_ZERO_BALANCE_ACCOUNT` `ON` in your environment and then test onboarding or/and import of a zero balance account. Note that only `mainnet` accounts need funding.
> feat: Skip funding step when creating implicit account

- packages/frontend/src/components/accounts/CreateAccount.js
- packages/frontend/src/components/login/v2/SelectAccountLogin.js
- packages/frontend/src/components/login/v2/SelectAccountLoginWrapper.js
- packages/frontend/src/components/login/v2/style/LoginStyle.css.js
- packages/frontend/src/components/wallet/DepositNearBanner.js
- packages/frontend/src/components/wallet/Wallet.js
Add the `<DepositNearBanner />` on the `/create` and `/login` pages when account is zero balance
> fix: Add 'deposit funds' banner to sign, create pages

- packages/frontend/src/components/staking/components/Validator.js
- packages/frontend/src/redux/createReducers/combinedMainReducers.js
- packages/frontend/src/redux/createReducers/combinedSharedReducers.js
- packages/frontend/src/redux/createReducers/index.js
- packages/frontend/src/redux/crossStateSelectors/selectCollectedAvailableForClaimData.js
- packages/frontend/src/redux/selectors/topLevel.js
- packages/frontend/src/redux/slices/tokens/index.js
- packages/frontend/src/redux/slices/tokensMetadata/index.js
The idea is to have two separate reducers:
1. `tokens` - that will be a part of account reducers
2. `tokensMetadata` - that will be shared between accounts.
> Refactor tokens reducer into two reducers

- packages/frontend/src/components/sign/v2/SignTransactionDetails.js
This PR fixes the order of `actions` on the Transactions Details page (Sign flow) by removing mutating the `transactions` array and replacing `.sort` function that results in changing the order of transactions in browsers without stable sort.
> Fix sorting actions for Sign Transaction Details page

- packages/frontend/src/components/accounts/CouldNotFindAccountModalWrapper.js
- packages/frontend/src/redux/slices/tokens/index.js
Three fixes:
1. Fix refreshing account, we need to wait till the `refreshAccount` action is resolved, even if currently it's throwing an error. That's because the active account is changed by `refreshAccount` action.
If we redirect to the dashboard before the `refreshAccount` is resolved, FTs are fetched for the precious account, because it's still an active account.
2. Fixed redirect. We should use `redirectToApp` instead of `redirectTo`. If for example the user will be redirected to Wallet to login to the app in case there is no imported account yet, and he will import a zero balance account, we should redirect the user to the `/login` page anyway, so user will be able to import different account and proceed with login.
3. Clean up the code formatting.
> When importing an implicit account it's showing FT data from a previous active account

- packages/frontend/src/components/swap/Swap.js
- packages/frontend/src/hooks/fungibleTokensIncludingNEAR.js
- packages/frontend/src/redux/selectors/crossStateSelectors/selectNEARAsTokenWithMetadata.js
This PR fixes reliance on NEAR token instances not having a `contractName` prop by only including that prop optionally and setting explicitly to true in cases where `contractName` is required
> fix: only include NEAR contractName with optional prop

- packages/frontend/src/components/accounts/account_selector/Account.js
- packages/frontend/src/components/common/ClickToCopy.js
Adds a "Copy to clipboard" button to the accounts list.
This required a nudge on the "Copied" text so that it doesn't cut off by the surrounding list.
Also changes the tooltip text to a description of what the button does.
Fixes https://github.com/near/near-wallet/issues/2620
> feat: add copy button to address list

- packages/frontend/src/translations/en.global.json
- packages/frontend/src/translations/it.global.json
- packages/frontend/src/translations/pt.global.json
- packages/frontend/src/translations/ru.global.json
- packages/frontend/src/translations/tr.global.json
- packages/frontend/src/translations/ua.global.json
- packages/frontend/src/translations/vi.global.json
- packages/frontend/src/translations/zh-hans.global.json
- packages/frontend/src/translations/zh-hant.global.json
- packages/frontend/test/translations.test.js
This PR adds escaping to the `href` on `v2.connectConfirm.desc` as well as a new test to catch missing quotes around `href` attributes across translation files.
> fix(translation): translation href escapes and validation

- packages/frontend/src/components/profile/Profile.js
- packages/frontend/src/components/profile/export_private_key/ExportKeyModal.js
- packages/frontend/src/components/profile/export_private_key/ExportKeyWrapper.js
- packages/frontend/src/components/profile/remove_account/RemoveAccountWrapper.js
- packages/frontend/src/images/icon-check-no-border.svg
- packages/frontend/src/images/icon-key.svg
- packages/frontend/src/images/icon-trash.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/utils/wallet.js
This PR:
1. Adds [functionality to show a modal, confirm `accountId` and view private key](https://nearinc.atlassian.net/browse/KWLT-6)
2. Adds an icon to the "Remove Account from Wallet" button
[Figma link](https://www.figma.com/file/w4SQVO6kBvAP5D65TGlm7y/Wallet-Domain-Migration)
> Kwlt 6 ability to export private keys

- packages/frontend/src/redux/sharedThunks/refreshAccountOwner.js
- packages/frontend/src/translations/en.global.json
Show an error toast with the text: `An error occured while loading your account. Some wallet data may not be up-to-date. Please try refreshing your browser.` if the `refreshAccountOwner` action throws an error.
> fix: Show error toast if there is an error loading account

- packages/feature-flags/src/index.js
This PR expands the "no environment set" error message to provide more context and enumerate the set of valid environments (values for `NEAR_WALLET_ENV` env var).
Closes #2564
> fix(env): more descriptive environment error

- packages/frontend/src/config/buyNearConfig.js
Near Pay link should point to `nearpay.co` not `nearpay.io`
> fix: fix near pay link

- packages/frontend/src/components/wallet/Wallet.js
This PR removes the rendering of `ReleaseNotesModal` from the main wallet page component. The information on this modal is currently woefully out of date and does not serve any productive purpose.
Until there's a process for keeping this updated with useful information it is better to not display it at all.
> chore: no longer render release notes modal

- features/features.d.ts
- features/flags.json
This PR turns the `SHOW_MIGRATION_BANNER ` feature flag off until further notice
> chore: flag migration banner off

- packages/frontend/src/config/buyNearConfig.js
https://mnw.atlassian.net/browse/MYNW-64
**Problem:**
MixPanel events were missing for UTORG, NearPay, RainbowBridge and all exchanges
**Fix:**
Added MixPanel events for this actions
> MYNW-64: add MixPanel events to top-up options

- packages/frontend/src/redux/crossStateSelectors/selectCollectedAvailableForClaimData.js
- packages/frontend/src/services/StakingFarmContracts.js
- packages/frontend/src/utils/account-with-lockup.js
This PR adds an additional condition in `isAccDeletable` for lockup accounts to check for unclaimed token rewards. `isAccDeletable` will affect whether the "Available to transfer" for the lockup includes the storage amount (3.5 / 35 Ⓝ) and whether we delete the lockup when withdrawing from it.
> Wal 277 withdrawing lockup funds issue

- packages/frontend/src/services/FungibleTokens.js
- packages/frontend/src/utils/gasPrice.js
Reference: https://nearinc.atlassian.net/browse/WAL-329
This PR queries RPC `get_price` to get the latest gas price. The `gas_price` is then used to estimate total fees when transferring fungible tokens.
For follow-up PR: Use `getTotalGasFee` to more accurately estimate fee's wherever a fee breakdown is shown
> feat: query RPC 'get_price' to estimate fees for token transfer

- Jenkinsfile
This PR updates the Jenkinsfile to ensure that `mainnet_STAGING` bundles are deployed when merging to `master`.
It also updates the bundling stages to only build bundles that will be deployed with the current pipeline. This change will expedite deployments triggered by merging to `stable`.
> feat(ci): Jenkins staging

- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/accounts/batch_import_accounts/BatchImportAccountsSuccessScreen.js
- packages/frontend/src/components/accounts/batch_import_accounts/sequentialAccountImportReducer.js
- packages/frontend/src/components/accounts/batch_ledger_export/AccountExportModal.js
- packages/frontend/src/components/accounts/batch_ledger_export/index.js
- packages/frontend/src/components/accounts/batch_ledger_export/styles.js
- packages/frontend/src/components/accounts/ledger/LedgerHdPaths.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/utils/wallet.js
This PR adds a batch export route to ledger wallet at `/batch-ledger-export` per [KWLT-24](https://nearinc.atlassian.net/browse/KWLT-24). It supports adding all non ledger accounts (phrase / 2fa) as ledger accounts which allows the user to use the ledger directly from a dapp or via the [wallet-selector](https://github.com/near/wallet-selector)
> feat: add batch export to ledger wallet route

- Jenkinsfile
- packages/frontend/package.json
This PR updates the CI configuration to run `yarn lint` before building, ensuring broken builds on branches with eslint rule violations. It also moves the local lint run to `prepush` from `precommit`, avoiding a 10+ second commit time and dropping the `--fix` to make it more difficult to push changes with eslint breaks.
> feat: linting enhancements

- features/features.d.ts
- features/flags.json
- packages/frontend/netlify.toml
- packages/frontend/src/config/environmentDefaults/development.js
- packages/frontend/src/config/environmentDefaults/mainnet.js
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.js
- packages/frontend/src/config/environmentDefaults/testnet.js
- packages/frontend/src/config/environmentDefaults/testnet_STAGING.js
This PR adds a new `RENDER_MIGRATION` feature flag which will update the API URL for contract helper to use the endpoints deployed to AWS. Since the `ACCOUNT_HELPER_URL` environment variable still needs to be overridden for local development, part of the rollout for this functionality requires that the environment variable is removed from the `near-wallet` build environments in render.com (testnet) and Netlify (mainnet). These variables are vestigial since the introduction of defined per-environment configurations and can be removed safely.
> feat: render.com migration

- Jenkinsfile
- features/flags.json
Prior to merging, the `REACT_APP_ACCOUNT_HELPER_URL` environment variable configured in render.com (testnet) must be removed.
> feat: enable RENDER_MIGRATION in testnet environments

- packages/frontend/src/config/environmentDefaults/development.js
- packages/frontend/src/config/environmentDefaults/mainnet.js
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.js
- packages/frontend/src/config/environmentDefaults/testnet.js
- packages/frontend/src/config/environmentDefaults/testnet_STAGING.js
Current REF_FINANCE_API_ENDPOINT is deprecated and doesnt work now.
This problem affected token exchange rates on wallet view.
This PR is updating mainnet/testnet endpoint URL for /list-token-price method according to information getting from directly messaging with guys from Ref Finance.
OLD: [https://indexer.ref-finance/list-token-price](https://indexer.ref-finance/list-token-price)
NEW: [https://indexer.ref.finance/list-token-price](https://indexer.ref.finance/list-token-price)
> fix: MYNW-72 Update ref.indexer endpoints

- packages/frontend/src/components/buy/BuyNear.js
- packages/frontend/src/components/buy/FundingCard.jsx
It was broken while there were more then 3 blocks.
before:
after:
> Fixed height of the top up page blocks

- packages/frontend/src/components/buy/BuyNear.js
Removed shuffling and updated order in Purchase NEAR section
> fix: remove shuffle from in Purchase NEAR section in top up page

- packages/frontend/src/components/wallet/DepositNearBanner.js
Changed banner address "Deposit Near" from `/recieve-money` to `/buy`
> fix: changed link in deposit near banner from /recieve-money to /buy

- packages/frontend/src/redux/slices/sign/index.js
- packages/frontend/src/routes/SignWrapper.js
Include `errorCode` and `errorMessage` as params in `signCallbackUrl` whenever a user rejects a sign transaction on the wallet side because of an error
> Fix (Sign TX): Include error in URL for DApp when TX is rejected because of error

- packages/frontend/src/services/indexer.js
- packages/frontend/src/tmp_fetch_send_json.js
- packages/frontend/src/utils/constants.js
This PR adds a custom request header to our requests made to contract-helper/indexer so that we can identify which requests to our backend come from near domains.
> feat: Add custom header requests to help identify near domains

- packages/frontend/package.json
- packages/frontend/src/components/accounts/RecoverAccount.js
- packages/frontend/src/components/navigation/AccessAccountBtn.js
- packages/frontend/src/config/configFromEnvironment.js
- packages/frontend/src/index.html
- packages/frontend/src/index.js
Changes:
1. Use `react-gtm-module` for Google Tag Manager to enable environment specific IDs
2. Add some initial tracking IDs for recovery buttons for testing in GTM
> chore: Use react-gtm-module vs manual script tag

- packages/frontend/src/components/common/Banner.js
- packages/frontend/src/components/common/RemoveLinkRecoveryBanner.js
- packages/frontend/src/components/wallet/Wallet.js
- packages/frontend/src/routes/WalletWrapper.js
- packages/frontend/src/translations/en.global.json
Add a banner on the wallet dashboard to encourage users to enable a passphrase or Ledger recovery method and disable all email and SMS recovery methods. The banner will only show if the currently active account has any email or SMS recovery methods.
More information is available on the near.org blog: https://near.org/blog/near-web-wallet-security-update/
> feat: Encourage users to disable link recovery methods

- packages/frontend/src/tmp_fetch_send_json.js
This PR removes the custom headers from `sendJson` requests, which currently yield CORS errors when calling out to `indexer.ref.finance` and is preventing token prices from loading. A follow-up PR will be required to ensure that all calls to the wallet indexer include the custom header.
> fix: don't send up custom headers on all requests from sendJson

- features/flags.json
Enables `RENDER_MIGRATION` in both `mainnet` and `mainnet_NEARORG` making wallet.near.org use the contract-helper service in AWS rather than Render.
> feat: Enable `RENDER_MIGRATION` in `mainnet` environments

- packages/frontend/README.md
Specify 'https' to avoid any confusion. Https is used because Ledger only supports a https connection.
> fix: specify https in readme getting started section

- packages/frontend/src/components/accounts/batch_import_accounts/sequentialAccountImportReducer.js
- packages/frontend/src/components/wallet-migration/Disable2FA.jsx
- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/translations/en.global.json
This PR adds a blocking modal forcing users to disable 2fa before they can proceed with the wallet migration
Design: https://www.figma.com/file/w4SQVO6kBvAP5D65TGlm7y/Wallet-Domain-Migration?node-id=1050%3A2322
Testing instructions:
1. Ensure `SHOW_MIGRATION_BANNER` flag is enabled
2. Create an account and enable 2fa
3. Initiate migration flow by clicking "Transfer my accounts" on the banner
4. You should not be able to migrate your account without disabling 2fa on that account
> feat: add blocking batch 2fa disable modal

- packages/e2e-tests/package.json
- packages/e2e-tests/utils/E2eTestAccount.js
- packages/e2e-tests/utils/helpers.js
This PR contains small update on fixing function on creating test seed phrase.
https://github.com/vacuumlabs/bip39-light#reminder-for-developers
previous:
> Update test account seed phrase with bip39Light

- packages/frontend/docs/NonFungibleTokenDiscovery.md
The doc missed the MINT event which is taken into account in the code:
https://github.com/near/near-contract-helper/blob/31710cd6e66022d4bfaa3756ed98f3aa42e37fdd/src/middleware/indexer.js#L182-L184
> fix(doc): Updated the information about NFT discovery

- packages/frontend/example.netlify.toml
- packages/frontend/netlify.toml
Also see: #2891 
Removed all .env variables from netlify.yaml
From now everything should be set in Netlify UI
Removed variables:
```
DISABLE_PHONE_RECOVERY = "yes"
REACT_APP_NETWORK_ID = "default"
REACT_APP_NODE_URL = "https://rpc.mainnet.near.org"
REACT_APP_ACCESS_KEY_FUNDING_AMOUNT = "250000000000000000000000"
NEW_ACCOUNT_AMOUNT = "500000001000000000000000000"
REACT_APP_ACCOUNT_ID_SUFFIX = "near"
EXPLORER_URL = "https://explorer.mainnet.near.org"
REACT_APP_IS_MAINNET = "true"
DISABLE_SEND_MONEY = "no"
DISABLE_CREATE_ACCOUNT = "true"
REACT_APP_MULTISIG_MIN_AMOUNT = "4"
LOCKUP_ACCOUNT_ID_SUFFIX = "lockup.near"
SENTRY_ORG = "near-protocol"
SENTRY_PROJECT = "mainnet-staging-wallet"
MOONPAY_API_KEY = "pk_live_jYDdkGL7bJsrwalHZs1lVIhdOHOtK8BR"
TOKEN_CONTRACTS = …
```
> MYNW-162: remove .env variables from netlify.yaml

- packages/frontend/src/utils/twoFactor.js
This PR addresses Issue #2885
Adds better visibility into errors while disabling 2fa
- If the user tries to disable the 2fa within the 15 minute cooldown period, they are told to wait 15 minutes. 
| User Cancels disable 2fa request      | User attempts to disable 2fa during cooldown |
| ----------- | ----------- |
| <img width="820" alt="image" src="https://user-images.githubusercontent.com/25015977/188217064-70f28632-9885-49d9-8751-4b24349bed32.png">      | <img width="881" alt="image" src="https://user-images.githubusercontent.com/25015977/188217105-55d976bb-d546-4405-914f-b7dd3fd94687.png">       |
> fix: disable2fa error messages

- packages/frontend/src/components/wallet/CreateCustomNameLightBanner.js
- packages/frontend/src/components/wallet/SidebarLight.js
* Made Explore Near banner always be the first in light Sidebar
* Fixed paddings for Custom Address banner on mobile light Sidebar
> fix: fixes for mobile light sidebar

- packages/frontend/src/components/profile/Profile.js
- packages/frontend/src/components/profile/Recovery/RecoveryContainer.js
- packages/frontend/src/components/profile/hardware_devices/HardwareDevices.js
- packages/frontend/src/redux/reducerStatus/handleAsyncThunkStatus.js
- packages/frontend/src/redux/reducerStatus/initialState/initialStatusState.js
- packages/frontend/src/redux/reducerStatus/manageStatus/setInitialized.js
- packages/frontend/src/redux/slices/recoveryMethods/index.js
- packages/frontend/src/utils/isEmptyError.js
- packages/frontend/src/utils/isEmptyError.test.js
Keep showing loading skeletons in case when loading failed with an error
A new status `isInitialized` is now available on every thunk.
`isInitialized` is set to `true` once thunk succeeds for the first time (and stays `true` even in case of errors).
Initial state is set to be `false`.
Recovery methods skeleton's are shown until `isInitialized` will be set to `true`.
> MYNW-196: fix(recovery-methods): skeletons for error

- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/common/TwoFactorDisableBanner.js
- packages/frontend/src/components/wallet-migration/AccountLock.jsx
- packages/frontend/src/components/wallet-migration/Disable2FA.jsx
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/utils/twoFactor.js
This PR contains implementation for showing Disable 2FA banner for near wallet.
(Please check [ticket](https://nearinc.atlassian.net/browse/WEP-99) for further details)
Banner
Modal
Account lock Modal (only show if target account is bricked)
Reset via passphrase
If anyone need help with manually creating bricked account, please let me know.
> WEP-99: Unbrick 2FA process to UI

- packages/frontend/netlify.toml
- packages/frontend/src/components/wallet-migration/AccountLock.jsx
- packages/frontend/src/components/wallet-migration/Disable2FA.jsx
The batch disable 2fa flow fails without any errors to the users. There are a few errors and hints we want to give the user:
- If the user tries to disable 2fa within 15 mins of each other for the same account
- The user hits cancel on the input 2fa code screen(let user know to wait 15 mins if they want to try again)
- When the user has a bricked account and enters the wrong key phrase into the modal.
> [WEP-161 ]fix: error handling

- packages/frontend/netlify.toml
removed NETLIFY_USE_YARN var as it is set in Netlify UI now. This will let forks build previews after this release.
> fix: removed NETLIFY_USE_YARN from Netlify.toml

- packages/frontend/src/components/common/TwoFactorDisableBanner.js
- packages/frontend/src/translations/en.global.json
This PR contains minor fix on TwoFactorDisableBanner component to allow foreign language translation.
Closes #2935 
Singular:
Plural:
> fix: update translation on TwoFactorDisableBanner

- packages/frontend/netlify.toml
Added `NETLIFY_USE_YARN=true` back into frontend/netlify.toml to fix build previews
> fix: define NETLIFY_USE_YARN in netlify.toml file

- packages/frontend/src/components/profile/Profile.js
- packages/frontend/src/components/profile/two_factor/TwoFactorAuth.js
Instead of graying out the 2fa Enable button in the 2fa component, we will remove the 2fa component all together to not confuse the user. 
The change will also effect MNW. 
If the user has 2fa enabled, they will still be shown the 2fa disable component.  
**Switching between an account with and without 2fa enabled**
**Disabling 2fa on an account**
> feat: remove modal all together unless the user has 2fa enabled

- packages/frontend/src/components/wallet-migration/SelectDestinationWallet.jsx
- packages/frontend/src/utils/isMobile.js
During wallet migration, only show `Finer Wallet` from migration list if the device is iOS.
[They](https://finerwallet.io/) only support iOS apps at the moment.
This is to avoid any android (and window 😄 ) phone users accidentally selecting  Finer Wallet.
> fix: only show Finer Wallet if device is iOS

- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/accounts/recovery_setup/new_account/ConfirmPassphrase.js
- packages/frontend/src/components/accounts/recovery_setup/new_account/SavePassphrase.js
- packages/frontend/src/components/common/MigrationBanner.js
- packages/frontend/src/components/wallet-migration/CommonComponents.jsx
- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/modals/Disable2faModal/AccountLock.jsx
- packages/frontend/src/components/wallet-migration/modals/Disable2faModal/Disable2FA.jsx
- packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/MigrationSecret.jsx
- packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/SelectDestinationWallet.jsx
- packages/frontend/src/components/wallet-migration/modals/RotateKeysModal/RotateKeysModal.jsx
- packages/frontend/src/hooks/getCurrentLanguage.js
- packages/frontend/src/images/IconOffload.js
- packages/frontend/src/translations/en.global.json
This PR contains minor UI updates on wallet migration:
([Design Reference](https://www.figma.com/file/FNtU2zIXEaMPuXaZDvK3IT/Wallet-Transition?node-id=701%3A28209))
this PR resolves #2959 
1. logged off state banner + label:
2. logged in state banner + label:
3. Wallet migration list:
4. Rotate Key Modal UI:
5. Rotate Key Modal Passphrase UI:
> Minor UI update on wallet migration [WEB-188]

- packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/SelectDestinationWallet.jsx
As requested for security reasons- this changes Meteor Wallet's batch import url to place the sensitive hashed data at the end of the URL as a URI parameter.
> Changed Meteor batch import to use URI hash

- features/flags.json
- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/svg/AlertRoundedIcon.js
- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/MigrateAccountsModal.jsx
- packages/frontend/src/components/wallet-migration/modals/MigrateAccountsModal/SelectDestinationWallet.jsx
- packages/frontend/src/components/wallet-migration/modals/VerifyingModal/VerifyingModal.jsx
- packages/frontend/src/components/wallet-migration/utils.ts
- packages/frontend/src/translations/en.global.json
This PR contains improvements on wallet migration:
1. Ability to auto save on important steps during migration.
Save points are:
- when user reach to transfer step (moving to other wallet)
- when user completes key clean up step (at this point there is no turning back)
- when user click start over button on verify step (This will remove save point and start from beginning)
2. Show tailored UI/view on third party wallet selection upon transferring ledger account(s)
A. When there is no ledger account, show everything
B. When there is only ledger account, show categorized view, ledger support, unsupported group
C. When there is mixture of ledger account(s) and FAK account(s), for the wallets that do not support ledger accounts, it will show info icon indicating that selecting unsupported …
> Wallet Migration UI/flow enhancement [WEB-175]

- features/flags.json
Disabling the migration feature on testnet since the flow is still being actively worked on.
> fix: Hide migration banner on testnet

- packages/frontend/src/components/common/TwoFactorDisableBanner.js
- packages/frontend/src/components/profile/Profile.js
- packages/frontend/src/components/profile/hardware_devices/ConfirmDisable.js
- packages/frontend/src/components/profile/two_factor/TwoFactorAuth.js
- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/modals/Disable2faModal/Disable2FA.jsx
- packages/frontend/src/components/wallet-migration/utils.ts
- packages/frontend/src/redux/actions/account.js
- packages/frontend/src/translations/en.global.json
This PR changes the components currently responsible for disabling 2FA so that they have awareness around whether a 2FA-enabled account requires that its keys are converted prior to attempting to disable 2FA. I'm not aware of a design for this so the exact wording and specifics on how the user is informed of this conversion (i.e. that they'll need to confirm multiple 2FA modals) is subject to change.
Disabling from `Disable 2FA` button:
> feat: batch key conversion in disable 2FA modal

- packages/frontend/src/services/NonFungibleTokens.js
This PR removes the outer `FunctionCallError(...)` string used to match error "missing method" responses from RPC. Currently mainnet errors do include this value but testnet RPC error responses do not, preventing NFTs from rendering.
> fix: remove outer FunctionCallError in NFT metadata error matching

- packages/frontend/src/components/accounts/two_factor/TwoFactorVerifyModal.js
This PR updates the code guard in the 2FA modal to match the expression being evaluated. This prevents the UI from breaking when the call to `get_request` fails.
> fix: verify actions exist

- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/CleanKeysModal.jsx
- packages/frontend/src/components/wallet-migration/modals/LogoutModal/LogoutModal.jsx
- packages/frontend/src/components/wallet-migration/modals/RedirectingModal/RedirectingModal.jsx
- packages/frontend/src/components/wallet-migration/modals/RotateKeysModal/RotateKeysModal.jsx
- packages/frontend/src/translations/en.global.json
This PR contains changes for wallet migration. 
A. Change the order of wallet migration steps to following:
1. Disable 2FA (if any)
2. Rotate Key
3. Delete FAKs
4. Export Account(s) to third party wallet (To be replaced with wallet-selector)
5. Logout
Intention of this change is to make sure we clean up FAKs before moving to third party wallet. (Also this is only way to make sure we don't accidentally delete any FAK(s) created by third party wallet)
B. Ability to come back and continue where user left
This is achieved by leaving current user's FAK that is used to log in on browser wallet from delete FAK(s) step. This key will be deleted on the final step `Logout`.
> feat: change the steps order on wallet migration

- features/flags.json
Enables recovery method/key cleanup and account export on wallet.testnet.near.org.
> feat: enable WEP_PHASE_ONE in testnet

- features/features.d.ts
- features/flags.json
- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/common/MigrationBanner.js
- packages/frontend/src/components/landing/GuestLanding.js
- packages/frontend/src/components/navigation/Navigation.js
- packages/frontend/src/translations/en.global.json
This PR updates the migration banner to include the current URL and keep account creation guarded behind a new flag (to be kept enabled on testnet for ease of testing). It also re-enables `WEP_PHASE_ONE` on testnet, allowing users to export accounts to available wallets.
> feat: migration banner URL

- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/utils.ts
This PR contains fix/improvements for wallet-migration from having corrupted accounts included in the list. 
As part of wallet-migration, it attempts to fetch extra detail for each available accounts within the browser prior to start of the migration. Previously if any one of account is corrupted (invalid key pair), the process stuck on initial step and unable to proceed to next step.
To fix this bug, it uses `Promise.allSettled` to gracefully handle the failed accounts and filter them out so migration can continue proceed regardless of presence of corrupted account key pairs. 
`console.log` is left there in case to be used on debugging/helping purposes if end user encounters them.
> Fix: filter out corrupted accounts and continue wallet-migration

- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/CleanKeysModal.jsx
- packages/frontend/src/config/environmentDefaults/mainnet.js
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.js
- packages/frontend/src/config/environmentDefaults/testnet.js
- packages/frontend/src/config/environmentDefaults/testnet_STAGING.js
Update `CleanKeysModal` to use the sanitized output of `accountWithDetails`. Currently, deleted accounts in your set of available accounts will break during key rotation.
> fix: use accountWithDetails in CleanKeysModal

- packages/frontend/src/components/accounts/recovery_setup/new_account/SavePassphrase.js
- packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/AccessKeyList.jsx
This PR contains minor UI update related to seed phrase modal with implicit account.
If fixes the UI by applying simple ellipsis:
> Minor UI update on handling implicit account character ellipsis

- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/modals/WalletSelectorModal/WalletSelectorModal.jsx
This PR contains a bug fix for account export where it was sending a private key from localStorage instead of newly created private key from key rotation step. 
Bug is fixed by sending a correct private key from `rotatedKeys` object. 
Conducted full end to end test to make sure that:
1. Correct private key is passed to other wallet
2. Upon logout, private key from localStorage gets deleted and rotated private key is still exist
3. After logout, attempt to transfer token from third party wallet that uses rotated private key to make sure it is available
> Bug fix on account export sending wrong private key

- packages/frontend/src/config/environmentDefaults/mainnet.js
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.js
- packages/frontend/src/config/environmentDefaults/testnet.js
- packages/frontend/src/config/environmentDefaults/testnet_STAGING.js
Partial revert of #3017 to remove debugging configuration that breaks only on wallet.near.org (staging unaffected).
> fix: reset to default

- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
This PR contains implementation for fixing the wallet migration wizard error. 
After reverting [this PR](https://github.com/near/near-wallet/pull/3036) , wallet migration wizard fail to operate properly as it was replying on `NETWORK_ID` to reflect the correct network. (eg. `testnet` or `mainnet`)
But revert needed to happen to fix another bug on wallet so wallet wizard also needed to make corresponding change in order to work properly.
> fix: avoid relying on NETWORK_ID to reference correct network

- packages/frontend/src/utils/sentry.js
This PR adds client-side filtering to Sentry reporting to redact sensitive information embedded within the URL, specifically by:
- removing the URL fragment component (only takes what comes before `#`)
- redacting strings with 12 space-delimited words
- redacting strings that could potentially be private keys
This change is to provide an extra assurance that private data is never reported to Sentry. The server-side Sentry integration for wallet.near.org already [strips all URLs which would contain sensitive information](https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/).
See Telegram post for more details: https://t.me/openvpn/190
> fix: redact sensitive data in URLs reported via Sentry

- packages/frontend/src/components/wallet-migration/modals/WalletSelectorModal/WalletSelectorExportContext.jsx
This PR contains implementation to include `My Near Wallet` back to mainnet supported wallet transfer list.
> feat: add My Near Wallet to mainnet export list

- packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/CleanKeysModal.jsx
This PR contains bug fix on `Clean Keys` step of wallet migration. 
Previous implementation had a bug where if there are two or more accounts being transferred, it was deleting FAK that is stored in localStorage. (Which it shouldn't be deleted) After investigation, the issue was using public key of first account. So the fix was made by selecting correct public key on each `accountId` given.
> Bugfix: Account Transfer Wizard clean key bug fix on multiple accounts

- packages/frontend/src/components/accounts/AccountListImport.js
- packages/frontend/src/components/common/Checkbox.js
- packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/AccessKeyList.jsx
- packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/CleanKeysModal.jsx
- packages/frontend/src/components/wallet-migration/modals/RotateKeysModal/RotateKeysModal.jsx
- packages/frontend/src/images/wallet-migration/IconKey.js
- packages/frontend/src/translations/en.global.json
This PR contains UI/UX improvements on clean key step of transfer wizard
Changes are as follow:
- Changed Icon
- Added more context
- Thick box colour change
- Added two private key with info icon to indicate why they can't be deleted at this step
- Updated expand icon
- Upon loading data for each account, it shows `Pending...` label only instead of showing both `x keys` and pending label.
> UI/UX improvements on clean key step (transfer wizard)

- packages/frontend/src/components/common/MigrationBanner.js
This PR contains minor link change on transfer wizard banner with logged out state
Upon clicking learn more button, it will redirect to a new static page `/transfer-wizard` which contains a info for transfer wizard process
> Minor link update on transfer wizard banner

- packages/frontend/package.json
- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/metrics.js
This PR contains changes from replacing Segment to Rudderstack. 
Currently these metrics are only active within wallet transfer functionality.
> Replacing Segment to RudderStack on transfer wizard metrics

- packages/frontend/src/components/wallet-migration/metrics.js
This PR contains minor update on RudderStack config to replace `DATA_PLANE_URL`. This PR must be merged and tested before releasing transfer wizard
> Update to a new data plane url on rudderstack config

- packages/frontend/src/components/wallet-migration/metrics.js
Minor bug fix on rudderstack config to use correct environment variable to match if target is staging or not.
> Fix: Use correct environment variable to match staging

- packages/frontend/src/components/wallet-migration/metrics.js
This PR contains fix for handling RudderStack upon blocked by ublock. 
It was working fine until recent test against Transfer Wizard on staging where it got stuck on initial loading state. It was caused by initial configuration on `RudderStack` due to a chrome extension called `ublock`. 
Therefore, I have implemented in a way that if it fail to establish the `RudderStack` initial config, it silently skips it and allow to proceed the wallet migration without metrics. 
Do not merge this PR if we decided to merge https://github.com/near/near-wallet/pull/3075 instead
> Handling rudderstack with adblock

- packages/frontend/src/translations/ru.global.json
This PR contains minor translation fix written in RU. We no longer support `startDate` and this part of translation only exist in RU. Based on commit date, it is very old and out dated. 
Before:
Now:
Thanks to @esaminu and other RU members on reporting this.
> Minor translation fix related to transfer wizard in RU

- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/metrics.js
- packages/frontend/src/components/wallet-migration/modals/CleanKeysModal/CleanKeysModal.jsx
This PR contains implementation to replace existing `account id` details on RudderStack metrics with hash id.
The team decided to not track account Id from RudderStack on Transfer Wizard. So similar to how it is implemented on `near-discovery` we hash the accountId and use it instead.
This change need to be published to prod as soon as it passes the review.
> Replace account id on rudderstack with hash id

- packages/frontend/src/components/common/MigrationBanner.js
- packages/frontend/src/components/svg/CloseIcon.js
- packages/frontend/src/components/wallet/Wallet.js
- packages/frontend/src/routes/TransferWizardWrapper.js
- packages/frontend/src/translations/en.global.json
- packages/frontend/src/translations/kr.global.json
- packages/frontend/src/translations/ru.global.json
This PR contains changes/improvements on Transfer Wizard:
1. UI changes on Transfer Wizard banner, more softer design
2. Banner detail changes in English, Russian and Korean (these are the only ones that has dedicated translation for transfer wizard)
3. Ability to close the banner and it will be hidden for a week. (Comes back after a week)
> Transfer wizard updates

- packages/frontend/src/translations/en.global.json
- packages/frontend/src/translations/kr.global.json
- packages/frontend/src/translations/ru.global.json
This PR contains update on migration label. 
Intention is to surface the message of `No changes will be made to your account or it's assets`. 
Removed KR and RU translation because we don't have time to wait. We are planning to post a message on wallet builder group to help us update on the translation.
> Update on wallet migration banner label

- packages/frontend/src/components/wallet/GetYourTickets.js
- packages/frontend/src/translations/en.global.json
> Release 2023-10-30

- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/modals/Disable2faModal/Disable2FA.jsx
- packages/frontend/src/components/wallet-migration/modals/WalletSelectorModal/WalletSelectorModal.jsx
Wallet migration team decided to skip the key rotation step to avoid further confusion and stress by users. 
This implementation contains slight change that will skip key rotation steps. (skipping creating new seed phrase and delete keys)
So far I have tested them on testnet environment and it work as expected.
> Wallet Migration skip Key rotation step

- packages/frontend/src/components/Routing.js
- packages/frontend/src/routes/TransferWizardWrapper.js
This PR contains minor change on transfer wizard doc to include call to action button at the bottom of the doc, allowing user to initiate the transfer wizard from doc page:
This button will only be visible if there is at least one account already signed in.
https://github.com/near/wallet-experience/issues/15
> Add Call To Action Button on Transfer Wizard Doc

- packages/frontend/src/components/wallet-migration/WalletMigration.jsx
- packages/frontend/src/components/wallet-migration/metrics.js
This PR contains two minor fixes:
1. Only track if event label is present
2. Let Rudderstack manage the when to send track event instead of explicitly checking `rudderAnalyticsReady` condition
Background:
During the implementation of new events regards to near wallet sunset, I have encountered that some of the events weren't firing to rudderstack even if they have `eventLabel` present. After investigation, I remembered that there was a condition in place to check rudderstack initialize complete and only then send track events. Previously it was enough to cater for wallet migration implementation. However, on near sunset, we are tracking events that occur during visiting landing page + visiting unsupported page and redirect event. This is normally happening in the very early stage of the …
> Minor bug fix on rudderstack

- packages/frontend/src/components/landing/GuestLanding.js
This PR contains small change, moving mobile wallet to last in the list:
Since this PR doesn't create any side-effect/functional change, please merge them as soon as it gets approved.
> Move mobile wallet UI to last in the list

- packages/frontend/src/components/common/Footer.js
Adding contact us to wallet.near.org in the footer linking to https://nearhelp.zendesk.com/hc/en-us/requests/new
CC: @reiokam
> feat(Footer): add contact us

- packages/frontend/src/components/Routing.js
- packages/frontend/src/components/wallet-migration/RecoveryRedirect.jsx
This PR contains implementation to support existing email link recovery method by automatically redirecting to my near wallet. 
To test on testnet locally, run:
```
yarn && NEAR_WALLET_ENV=testnet yarn start
```
with [this link](https://localhost:1234/recover-with-link/testtest12312.testnet/slim%20cluster%20aisle%20option%20rose%20pact%20shadow%20decade%20employ%20duck%20flush%20spray) will redirect to [mynearwallet testnet](https://testnet.mynearwallet.com/recover-with-link/testtest12312.testnet/slim%20cluster%20aisle%20option%20rose%20pact%20shadow%20decade%20employ%20duck%20flush%20spray)
I have also tested it against mainnet by:
```
yarn && NEAR_WALLET_ENV=mainnet_NEARORG yarn start
```
with mainnet account, (please ping me if you need them to test)
will redirect to:
> feat: email recovery link to redirect to my near wallet

- packages/frontend/src/translations/en.global.json
The new landing page's mobile view has an h2 element with the scrunched font. This PR resolves this by adding line-height
Before:
After:
> fix: resolve landing page h2 element mobile view
